### PR TITLE
Upload: add ajax error response object to err

### PR DESCRIPTION
**Pull request by Bennnis**
Please make sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by Bennnis** [comment]
https://github.com/ElemeFE/element/issues/9384

**Comment by Leopoldthecoder** [comment]
Please write a demo on this issue, and add some description about how this PR can help with the situation.

**Comment by Bennnis** [comment]
help someone who need to deal with err response object.

**Comment by Leopoldthecoder** [comment]
Please write a online demo.

**Comment by Bennnis** [comment]
my pr is not enough？I cant write a demo because i dont wanna write build a server to response with 500

**Comment by wacky6** [comment]
you can ajax to any non existing page to get a 404

**Comment by Bennnis** [comment]
i wanna got 500 with response

**Pull request closed without merging**
