### PR TITLE
Table: add remote sort support.

### PR DESCRIPTION
**Pull request by yiidot**
Table: add remote sort support.
It prevents front-end sort while sort-mode is 'remote'.

Please make sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by yiidot** [comment]
done.

**Comment by yiidot** [comment]
usage:
<el-table-column
    ...
    sortable
    :sort-mode="'remote'">
</el-table-column>

**Comment by ziyoung** [comment]
@yiidot which issue does this pr fix? Please provide a simple demo.

**Comment by yiidot** [comment]
@ziyoung it maybe a new issue. Without sort-mode, data sorted on server will be sorted again on the front end, which may turn data to wrong order.Please see the attachment for example.
[table-remote-sort.zip](https://github.com/ElemeFE/element/files/2556187/table-remote-sort.zip)

**Pull request closed without merging**
