### PR TITLE
Update test config

### PR DESCRIPTION
**Pull request by QingWei-Li**
Please makes sure these boxes are checked before submitting your PR, thank you!

* [ ] Make sure you follow Element's [Contributing Guide](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.md).
* [ ] Rebase before creating a PR to keep commit history clear.
* [ ] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by QingWei-Li** [comment]
真好 ci 时间又压缩下来了

**Comment by Leopoldthecoder** [comment]
只是去掉 lint 就能节省一半多的时间？

**Comment by QingWei-Li** [comment]
肯定啊 eslint-loader 挺费时间的

**Comment by QingWei-Li** [comment]
感人
现在的覆盖率才是正确的，之前配置错了

**Pull request merged**
