### PR TITLE
Package.json: Update async-validator to support "function" as input for message.

### PR DESCRIPTION
**Pull request by JBtje**
Update async-validator version
As of 1.11.1, it supports functions for the message parameter.

Please make sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by JBtje** [comment]
@iamkun can I bother you for an inspection of this merge request? By updating the package, support for "function" as message is added.

**Comment by ziyoung** [comment]
We will update dependencies in the next major version. So right now this pr won't be merged.

**Comment by JBtje** [comment]
@ziyoung can you add this to the next major milestone, so it won't be forgotten?

**Comment by iamkun** [comment]
@JBtje Sure thanks

**Comment by JefferyHo** [comment]
The latest tag and the DEV branch still not support "function" as input for message.

**Pull request closed without merging**
