### PR TITLE
Form: fix validate message does not be displayed correctly when message is a function

### PR DESCRIPTION
**Pull request by luoshuqi**
Please make sure these boxes are checked before submitting your PR, thank you!

* [ ] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [ ] Make sure you are merging your commits to `dev` branch.
* [ ] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by WaSheep** [comment]
please provide a demo

**Comment by luoshuqi** [comment]
[demo: https://luoshuqi.github.io/](https://luoshuqi.github.io/)
[代码: https://github.com/luoshuqi/luoshuqi.github.io/blob/master/App.vue](https://github.com/luoshuqi/luoshuqi.github.io/blob/master/App.vue)

**Comment by WaSheep** [comment]
Please synchronize the relevant documents

**Comment by luoshuqi** [comment]
原来不是bug。async-validator 是在 1.11.1 才支持message为function的，element用的是1.8。

**Pull request closed without merging**
