### PR TITLE
Dialog: Add transition name as a prop (with default value for reverse compatibility)

### PR DESCRIPTION
**Pull request by SabatinoMasala**
I added the transition name as a prop on the dialog component, with a default value of 'dialog-fade'. This way we can fully control the transition of the dialog.

### CODE REVIEW

**Comment by Leopoldthecoder** [comment]
Hi, thanks for contributing.

Customizing Dialog animation does not seem to be a common request, so we may not add a prop to do that. Actually you can do so by overriding its CSS: https://jsfiddle.net/qs0cod48/

**Comment by SabatinoMasala** [comment]
@Leopoldthecoder, agreed, but my main concern was about being able to disable the transition.

[Other components](https://github.com/ElemeFE/element/blob/dev/packages/tag/src/tag.vue#L2) offer a 'disableTransitions' prop, I could send a PR with an implementation in the dialog, if that fits better? I agree that this would be more consistent than adding the transition name as a prop.

**Comment by Leopoldthecoder** [comment]
Disabling transitions is actually something we can work on. Maybe we'll try to implement it so that
```JS
Vue.use(Element, { transitions: false })
```
can turn off all popup transitions (Dialog, MessageBox, Select, Dropdown, etc.).

For now you can disable Dialog's transition with CSS: https://jsfiddle.net/qs0cod48/1/ . Note that I also disabled backdrop's transition as well in the demo, otherwise it would look kinda weird.

**Comment by SabatinoMasala** [comment]
Sounds very interesting, so we'd store the `transitions` bool on the ELEMENT config variable...
```js
...

ELEMENT.transitions = opts.transitions || true;

Vue.prototype.$ELEMENT = ELEMENT;
```

...and then in components we'd check whether or not to add a transition name:

```vue
<transition :name="$ELEMENT.transitions ? 'el-zoom-in-center' : ''">
  ...
</transition>
```

Seems a bit cleaner than overriding the CSS imo, but happy to hear your thoughts!

A note about reverse compatibility: Would you keep the `disableTransitions` prop on the Tag for example, or strip it out entirely?

**Comment by Leopoldthecoder** [comment]
Yes, we'll keep Tag's `disableTransitions`. And it should have a higher priority than `$ELEMENT.transitions`.

**Comment by SabatinoMasala** [comment]
Great, I will send a PR!

**Pull request closed without merging**
