### PR TITLE
fix theproblem forget to  PluginObject

### PR DESCRIPTION
**Pull request by notcold**
export const InfiniteScroll: PluginObject<ElInfiniteScroll>;
 the PluginObject  didnt import before

Please make sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by notcold** [comment]
https://github.com/ElemeFE/element/pull/15821

**Comment by notcold** [comment]
昨天修复问题引入PluginObject 并没有加import导致ts校验还是存在问题

**Comment by marcomonsanto** [comment]
any updates on when will you merge?

**Comment by WaSheep** [comment]
Duplicate of #15805

**Comment by li1224632854** [comment]
为啥2.9.1版本 这个错误还是存在

**Comment by notcold** [comment]
> 为啥2.9.1版本 这个错误还是存在

看git代码是修复，但是新修复的版本还没发布，所以建议还是先降一下版本

**Pull request closed without merging**
