### PR TITLE
Notification: Support HTML, close #1885

### LINKED ISSUE #1885: [Notification]support HTML escaping
### ElementUI version
1.0.5

### OS/Browers version
Windows 7, Chrome 55

### Vue Version
2.1.6

### What is the Request?
When using the notifications ($notify), it would be nice if you provide an option to suppress the HTML escaping. In my case I want a linebreak, but it is not possible. $notify displays `<br />` as a string.
Maybe you can provide two options:
one for general escape supress and another for automatic conversion between \r\n to `<br />`.

### PR DESCRIPTION
**Pull request by QingWei-Li**
Please makes sure these boxes are checked before submitting your PR, thank you!

* [ ] Make sure you follow Element's [Contributing Guide](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.md).
* [ ] Make sure you are merging your commits to `dev` branch.
* [ ] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by Leopoldthecoder** [comment]
另外用 `v-html` 真的好吗？@baiyaaaaa 觉得呢？

**Comment by QingWei-Li** [comment]
新黑科技 支持 VNode。喜欢么 🌚

**Comment by QingWei-Li** [comment]
@reverland 如果 Vue 有类似 `React#createElement` 的 API 的话，搭配 JSX 用法就会爽很多。字符串的 html 也未尝不可，只是看到 antd 这样搞，我只是想试试看

```js
this.$notify.error(<p style={ color: 'red' }>吼不吼啊</p>)
```

**Comment by baiyaaaaa** [comment]
香草的味道

**Pull request merged**
