### PR TITLE
table: fix treeTable expand-row-keys and default-expand-all

### PR DESCRIPTION
**Pull request by meihuanyu**
Please make sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by meihuanyu** [comment]
[14884](https://github.com/ElemeFE/element/issues/14884)

**Comment by meihuanyu** [comment]
[14884](https://github.com/ElemeFE/element/issues/14884),[14933](https://github.com/ElemeFE/element/issues/14933),[14904](https://github.com/ElemeFE/element/issues/14904)

**Comment by meihuanyu** [comment]
[14973](https://github.com/ElemeFE/element/pull/14973)try this pr, init invalid

**Comment by meihuanyu** [comment]
GIF
init defaultExpandAll 
expandRowKeys controlled expand

**Comment by ziyoung** [comment]
Please read the doc carefully. `default-expand-all` and `expand-row-keys` only work when expand column exists.

**Comment by ziyoung** [comment]
| Attribute | Description |
| -| -|
| default-expand-all | whether expand all rows by default, only works when the table has a column type="expand"|
| expand-row-keys | set expanded rows by this prop, prop's value is the keys of expand rows, you should set row-key before using this prop|

**Comment by meihuanyu** [comment]
So is TreeTable solution a new attribute? @ziyoung

**Comment by meihuanyu** [comment]
this pr compatible expand column

**Comment by ziyoung** [comment]
> this pr compatible expand column

Yes, it works. But this means that an attribute has two different capabilities. We have to write more docs to explain the usage in detail.

**Comment by meihuanyu** [comment]
> > this pr compatible expand column
> 
> Yes, it works. But this means that an attribute has two different capabilities. We have to write more docs to explain the usage in detail.

So are you going to take my advice?

**Comment by ziyoung** [comment]
see issue #15170

**Comment by donvan** [comment]
only expand,  how to un-expand 折叠？

**Comment by donvan** [comment]
only expand,      how to un-expand all 折叠？

**Pull request closed without merging**
