### PR TITLE
French translation

### PR DESCRIPTION
**Pull request by smalesys**
Please make sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer relative issues for you PR.

---

Hello !

This is my small contribution to the french translation. If you are interested in going further, would you need some help ? Or do you have already some plans for it ?

### CODE REVIEW

**Comment by ziyoung** [comment]
@smalesys Thanks for your contribution. We are very happy that the document can be translated into French.

**Comment by smalesys** [comment]
Great, i will work on it :)

**Comment by wacky6** [comment]
Thanks for your interest in contributing.

@jikkai @ziyoung I would recommend finding more contributors for French translation. The Spanish translation issue can be used as a reference https://github.com/ElemeFE/element/issues/8074

**Comment by smalesys** [comment]
That's a good idea, i will continue on my own to work on it since i have a bit of time during August.
If you open an official issue it will probably attract some french contributors indeed.

**Comment by smalesys** [comment]
Sorry, i must admit that due to work pressure these last months i completed forgot about it several times. Im on vacations for a few days now so i'll try to get back on track.

**Comment by smalesys** [comment]
@wacky6 @jikkai @ziyoung Almost done :)

Only the Changelog to do i think. I'll also need to review all of it and probably update according to the last patches. Tell me if anything is going the wrong way.

**Comment by wacky6** [comment]
LGTM

**Comment by smalesys** [comment]
@wacky6 I am currently focusing on the changelog and then i will update to `2.5.0` version. 

And sure, i would be glad to continue updating the docs in French :)

**Comment by smalesys** [comment]
@wacky6 @island205 I think we're good to go :) tell me if its ok for you.
It works smoothly on my computer but i may have missed some spots.
I also noticed a few bugs with anchor links but apparently not related to the translation.

**Comment by island205** [comment]
@smalesys Great work, Thank you very much!

**Pull request merged**
