### PR TITLE
[form] fix style when error

### PR DESCRIPTION
**Pull request by romoo**
Please makes sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer relative issues for you PR.

fix: #2780

### CODE REVIEW

**Comment by baiyaaaaa** [comment]
为什么要加这个？

**Comment by baiyaaaaa** [comment]
这个会影响到el-select 单独使用时的验证样式，应该覆盖的是 el-input-group__prepend 和 el-input-group__append 下的input边框样式

**Comment by romoo** [comment]
复合型输入框出错时样式有问题，issue 里有截图

**Comment by romoo** [comment]
我改下

**Pull request merged**
