### PR TITLE
add .sync support for Dialog and Pagination

### PR DESCRIPTION
**Pull request by Leopoldthecoder**
Please makes sure these boxes are checked before submitting your PR, thank you!

* [ ] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md)).
* [ ] Make sure you are merging your commits to `dev` branch.
* [ ] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by QingWei-Li** [comment]
breaking change？

**Comment by Leopoldthecoder** [comment]
Doesn't break anything unless you are using Dialog like
```html
<el-dialog :value="visible">
```

**Comment by baiyaaaaa** [comment]
虽然是一个 breaking change， 不过理论上来说，使用 `:value="visible"` 的应该很少将近没有

**Comment by sabakugaara** [comment]
原先用法 `v-model='dialogVisble'` 升级兼容吗？

**Comment by Leopoldthecoder** [comment]
@sabakugaara 兼容

**Comment by sabakugaara** [comment]
多谢，请问这种调整，仍然兼容，是 vue2 的机制吗？

**Comment by Leopoldthecoder** [comment]
@sabakugaara Dialog 内部的 v-model 仍然存在，只是改了个名字不再叫 `value` 了。改名这个 feature 是 Vue 2.2 引入的。

**Pull request merged**
