### PR TITLE
Slider: added bi-directional support to slider

### PR DESCRIPTION
**Pull request by anatoly314**
Please make sure these boxes are checked before submitting your PR, thank you!

* [ x] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md)).
* [ x] Make sure you are merging your commits to `dev` branch.
* [ x] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by ziyoung** [comment]
@anatoly314 format your code and tell us which feature is added.

**Comment by Tlapi** [comment]
I see, this is adding something like that.

bidir

Exactly what I am looking for ;-)

**Comment by anatoly314** [comment]
@Tlapi , Yes it's functionality I've been added. I will try to reformat my code and submit this pull request on this weekend.

**Comment by ziyoung** [comment]
@anatoly314 netlify build failed.

**Pull request closed without merging**
