### PR TITLE
Tag: add tag click event handle

### PR DESCRIPTION
**Pull request by licdream**
Please make sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer relative issues for you PR.

Add click event handle to tag component.

### CODE REVIEW

**Comment by island205** [comment]
more description about this change?

**Comment by licdream** [comment]
The tag component just exposed a close event at current version. This change exposed a click event of tag.  I think a click event is frequently used.

**Comment by licdream** [comment]
I have committed the doc and unit test, please review them.

**Comment by island205** [comment]
@ziyoung

**Pull request merged**
