### PR TITLE
[table-column] add render header index

### PR DESCRIPTION
**Pull request by kolesoffac**
Please make sure these boxes are checked before submitting your PR, thank you!

* [ ] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md)).
* [ ] Make sure you are merging your commits to `dev` branch.
* [ ] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by Leopoldthecoder** [comment]
What is the use case for this feature?

**Comment by kolesoffac** [comment]
1 - render function is there for other column, so why don't use same for index column
2 - sometimes don't want use only text for first column(and is it index column), exemple, use some ui-control

**Comment by Leopoldthecoder** [comment]
OK. Please update the docs and add a test case for this feature. Also, I think `renderIndexHeader` is more accurate than `renderHeaderIndex`.

**Comment by kolesoffac** [comment]
Good, i will do.

**Pull request closed without merging**
