### PR TITLE
DatePicker: fix readonly, add disabled and editable, fixed #976

### LINKED ISSUE #976: Date picker the readonly doesn't work
### ElementUI version
1.0.0

### OS/Browers version
macOS Sierra/Chrome 54.0.2840.71

### Vue version
2.0.4

### Reproduction Link
[Example](https://jsfiddle.net/gil0mendes/k21f7405/1/)

### What is Expected?

When the `readonly` prop is set to `true` the datepicker must be readonly and the value can't change.

### What is actually happening?

The `readonly` prop doesn't change the element behaviour.

## Suggestion

In order to follow the same pattern as the other input elements the `readonly` prop could be renamed to `disabled`.

### PR DESCRIPTION
**Pull request by QingWei-Li**
Please makes sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's [Contributing Guide](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.md).
* [x] Rebase before creating a PR to keep commit history clear.
* [x] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by Leopoldthecoder** [comment]
冲突了。

**Comment by QingWei-Li** [comment]
@Leopoldthecoder 杨老师看看翻译要不要改 🌚

**Comment by Leopoldthecoder** [comment]
没事，合了我一起改。倒是 Changelog 里要不要写 Breaking change？@furybean 觉得呢？

**Comment by furybean** [comment]
感觉不是 breaking change，只是之前没实现预期的功能。

**Pull request merged**
