### PR TITLE
Input: 修复input的suffix高度溢出的问题

### PR DESCRIPTION
**Pull request by fxxjdedd**
Please make sure these boxes are checked before submitting your PR, thank you!

* [ ] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [ ] Make sure you are merging your commits to `dev` branch.
* [ ] Add some descriptions and refer relative issues for you PR.

el-input在el-form-item之中时，suffix高度会溢出

image

[复现链接](https://codepen.io/anon/pen/JqEBxw?&editable=true)

### CODE REVIEW

**Comment by zhouyu1993** [comment]
get it

**Comment by luckyCao** [comment]
2.9.1 版本已经修复这个问题

**Comment by WaSheep** [comment]
The issue has been resolved, please update your version

**Comment by fxxjdedd** [comment]
got it

**Pull request closed without merging**
