### PR TITLE
DatePicker: fix range-separator not working with more than one instances

### PR DESCRIPTION
**Pull request by Leopoldthecoder**
Please makes sure these boxes are checked before submitting your PR, thank you!

* [ ] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md)).
* [ ] Make sure you are merging your commits to `dev` branch.
* [ ] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by Leopoldthecoder** [comment]
#3174

**Comment by QingWei-Li** [comment]
这个支票没问题

**Comment by OuYancey** [comment]
This merge seems to cause bugs: [#3503](https://github.com/ElemeFE/element/issues/3503), [#3479](https://github.com/ElemeFE/element/issues/3479)

**Comment by Leopoldthecoder** [comment]
@OuYancey This doesn't cause #3479. Plus #3503 is not a bug.

**Comment by OuYancey** [comment]
@Leopoldthecoder sry, my mistake.

**Pull request merged**
