### PR TITLE
misc visual updates

### PR DESCRIPTION
**Pull request by Leopoldthecoder**
Please makes sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's [Contributing Guide](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.md).
* [x] Rebase before creating a PR to keep commit history clear.
* [x] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by QingWei-Li** [comment]
image

**Comment by csvwolf** [comment]
冲突？

**Comment by Leopoldthecoder** [comment]
嗯，先等等，我待会还有个 commit

**Comment by Leopoldthecoder** [comment]
求合。然后你们就能看到深空灰版首页了。

**Comment by QingWei-Li** [comment]
lgtm

**Pull request merged**
