### PR TITLE
#4261: [Table] Add slot to support infinite loading components

### PR DESCRIPTION
**Pull request by syn-zeta**
Where would be an appropriate place in `table.md` to document the slot?

* [x] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by syn-zeta** [comment]
Where can this slot be documented in `table.md`?

**Comment by Leopoldthecoder** [comment]
For this slot, we have much more to consider. We'll try to implement this later.

**Comment by syn-zeta** [comment]
@Leopoldthecoder Can you please comment on what needs to be considered so I could think about it and perhaps improve my solution?

**Comment by Leopoldthecoder** [comment]
image

@syn-zeta There are feature requests asking for a place to put a summary row, and that's why we wanted to bring in an extra bottom slot, where you can also implement infinite loading.

This slot should work well when there're fixed columns, and of course itself can be fixed at the bottom. Please let me know if you are interested.

**Comment by syn-zeta** [comment]
@Leopoldthecoder Makes sense.
Although I would like to, I have to spend some time digging into how Element and Vue work as I'm new to web dev in general, before making any significant contributions. Still, can you point me to the feature requests for the summary row? And it would be very helpful if you could share in those threads what would be an ideal way to implement the feature, and I can take a whack at it.

**Comment by Leopoldthecoder** [comment]
No worries, I'm already working on it.

**Comment by Leopoldthecoder** [comment]
@syn-zeta 1.3.0-beta.1 is out, please check if [this slot](http://element.eleme.io/#/en-US/component/table#table-slot) works for you.

**Comment by rodwin** [comment]
HI @syn-zeta 
Do you have a guide on this? The documentation on table for infinite scroll is very limited. Appreciate your help. Thanks

**Comment by syn-zeta** [comment]
Hello @rodwin. I found a simple fiddle where I was experimenting with `vue-infinite-loading` and ElementUI's Table components: https://jsfiddle.net/8mvnsa22/

It a rather simple example, and should be fairly self-explanatory. Hope it helps.

**Comment by rodwin** [comment]
@syn-zeta 
Thanks for this.

**Comment by imkiven** [comment]
i have a problem to use it , https://github.com/ElemeFE/element/issues/6642

**Comment by naifen00** [comment]
el-table + vue-infinite-loading
https://peachscript.github.io/vue-infinite-loading/guide/use-with-el-table.html

**Pull request closed without merging**
