### PR TITLE
chore: use codepen to display demo & fix doc error

### PR DESCRIPTION
**Pull request by ziyoung**
Please make sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by iamkun** [comment]
LGTM

**Comment by wacky6** [comment]
我觉得jsfiddle可以留着啊 🤔 小规模写还是很开心的

**Comment by iamkun** [comment]
@wacky6 主要是遇到了 jsfiddle 可访问性的问题🤔

**Comment by ziyoung** [comment]
@wacky6 看来澳洲的网络比国内要好。🙃

**Comment by wacky6** [comment]
😂 在国内的话。穿墙不是基本技能吗。而且element不只国内用户呀。

**Pull request merged**
