### PR TITLE
Smaller size for components (#14850)

### LINKED ISSUE #14850: [Feature Request] A smaller size for components
### Existing Component
Yes

### Component Name
Button, Radio, Checkbox, Input, InputNumber, Select, TimePicker, DatePicker, DateTimePicker, Table, Tag, Dropdowns, Forms

### Description
Some Element components have a size attribute - but even the smallest size ('mini') seems to be too big in certain instances. I'm proposing adding a new size called 'compact'. The size should look consistent across all components the way mini does. Documentation for these components sizes should also be updated.

### PR DESCRIPTION
**Pull request by amedora**
Please make sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer relative issues for you PR.

close #14850

### Sub PRs

- [x] Button (#15895)
- [x] Cascader (#15896)
- [x] Checkbox (#15897)
- [x] DatePicker & DateTimePicker (#15898)
- [x] Dropdowns (#15899)
- [x] Forms (#15900)
- [x] Input (#15901)
- [x] InputNumber (#15902)
- [x] Radio (#15903)
- [x] Select (#15904)
- [x] Table (#15905)
- [x] Tag (#15906)
- [x] TimePicker (#15907)

### CODE REVIEW

**Comment by ChuckFields** [comment]
@amedora This is awesome! I took a look at the preview and I have a few comments.
- The round compact button in the preview has size="Compact" instead of size="compact" so it looks the same as default.
- An el-radio-group with el-radio-buttons does not work with compact, however it does work if you use el-radios instead of el-radio-buttons.
- How hard would it be to make the el-date-pickers popup panel reflective of it's size?
- How hard would it be to make the el-options inside of el-selects reflective of it's size?

**Comment by amedora** [comment]
@ChuckFields thanks for your feedbacks.

> * The round compact button in the preview has size="Compact" instead of size="compact" so it looks the same as default.
> * An el-radio-group with el-radio-buttons does not work with compact, however it does work if you use el-radios instead of el-radio-buttons.

oops, those were my mistake. fixed them now.

> * How hard would it be to make the el-date-pickers popup panel reflective of it's size?
> * How hard would it be to make the el-options inside of el-selects reflective of it's size?

Both doesn't have size option so there will be a lot of things to do.

**Comment by ChuckFields** [comment]
@amedora Okay no problem, those last 2 are just nice-to-haves.

**Comment by wacky6** [comment]
@amedora There are conflicts in *.md files, please take a look.

This feature looks good, we will try to include it in next release.

**Comment by amedora** [comment]
@wacky6 Thanks! Now rebased to current dev branch.

**Comment by island205** [comment]
1. please resolve conflicts
2. spliting this PR to small PR which just modify one component is more readable.

**Comment by amedora** [comment]
> 1. please resolve conflicts
> 2. spliting this PR to small PR which just modify one component is more readable.

Sure. I will do that later :+1:

**Comment by island205** [comment]
I am very sorry, Refer to our designer's opinion, we have no plan to support this at this time.

**Comment by amedora** [comment]
@island205 I see. Thanks for taking care of this PR.

**Pull request closed without merging**
