### PR TITLE
Tabs: add disabled feature

### PR DESCRIPTION
**Pull request by Kingwl**
Please makes sure these boxes are checked before submitting your PR, thank you!

* [ ] Make sure you follow Element's [Contributing Guide](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.md).
* [ ] Make sure you are merging your commits to `dev` branch.
* [ ] Rebase before creating a PR to keep commit history clear.
* [ ] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by baiyaaaaa** [comment]
加功能把测试也加上吧

**Comment by Kingwl** [comment]
@baiyaaaaa 已加

**Comment by Leopoldthecoder** [comment]
OK，今天的版本赶不上了，等我们和设计商量一下视觉，可能放在下个版本里。

**Comment by Kingwl** [comment]
木有事情。。。

**Comment by baiyaaaaa** [comment]
#1279

**Comment by baiyaaaaa** [comment]
没有做移除tab时下一个激活的tab是否为disabled状态的判断处理

**Pull request closed without merging**
