### PR TITLE
TableBody: split render function into few smaller ones

### LINKED ISSUE #14471: [Feature Request] Allow to provide custom table-body implementation
### Existing Component
Yes

### Component Name
el-table

### Description
I want to implement infinite scrolling by using el-table component and track visible page with [IntersectionObserver API](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API). 

For example, each page contains 50 elements. I want to group 50 `<tr>` tags inside one `<tbody>`. In such way, each tbody contains elements for a single page. Then I can track when one tbody appears and another disappears to track when to switch `page` parameter in browser url.
Currently I can do this by overwriting `Table.components.TableBody` but this is a hacky solution. 

So, there are several ways to fix this:
1. Implement a factory function which can create Table component on the fly with specified parts:
```js
import { createTable } from 'element-ui'

const Table = createTable({
  body: MyCustomBody, 
  footer: MyCustomFooter
})
```
2. A bit simpler: split `Table`'s `render` function into several smaller functions (e.g., `renderBody`, `renderFooter`, etc). So, then I can extend component and overload that functions:
```js
export default {
  name: 'MyCustomTable',
  extends: ElTable,
  methods: {
    renderBody(context) {
      return this.$createElement(MyCustomBody, context)
    } 
  }
}
```

### PR DESCRIPTION
**Pull request by stalniy**
Fix #14471

Please make sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer relative issues for you PR.

In this PR, I exported `TableBody` as public component and refactored its `render` function so that `TableBody` can be inherited and extended. This allows to create custom `Table` components with custom logic (e.g., for infinite loading). Example usage:

```js
import Table from 'element-ui/lib/table'
import TableBody from 'element-ui/lib/table-body'

const MyTableBody = {
  name: 'MyTableBody',
  extends: TableBody,
  methods: {
    renderBody(rows) {
       // custom body render implementation
      return this.$createElement('tbody', null, this.renderRows(rows))
    }
  }
}

export default {
  name: 'MyTable',
  extends: Table,
  components: {
     TableBody: MyTableBody
  }
}import MyTableBody from './MyTableBody.vue'

export default {
  name: 'MyTable',
  extends: Table,
  components: {
     TableBody: MyTableBody
  }
}
```

### CODE REVIEW

**Comment by ziyoung** [comment]
@stalniy awesome. I am going to add a new component called `ElTreeTable` (#15170). This may conflict with your pr. After TreeTable is finished, I will review your pr.

**Comment by stalniy** [comment]
Why don’t you want to review and then start working on TreeTable? 

I suppose it can be written on top of el table. In my vision, you could just create a custom TableBody for this. Actually there is already some logic for tree-like expands in current implementation of TableBody

**Comment by P8TRO** [comment]
@stalniy if you have a minute could you resolve these conflicts? I would love to see this get merged. I'd really like to start implementing a customer renderer as the non-virtual el-table performance is getting unbearable for our team. thanks!

**Comment by stalniy** [comment]
@P8TRO The table body was so, heavily refactored... This PR also refactors table-body, so eventually this work should be thrown away and I need to start over :(

**Pull request closed without merging**
