### PR TITLE
Upload: optimize code (#13786)

### PR DESCRIPTION
**Pull request by elfman**
Please make sure these boxes are checked before submitting your PR, thank you!

* [ ] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md)).
* [ ] Make sure you are merging your commits to `dev` branch.
* [ ] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by island205** [comment]
For what?

**Comment by wacky6** [comment]
写法习惯。

原先写法forEach中修改了被循环量的值。语义上map更合适。

个人倾向是尽量往immutable的思路上靠。非POD值修改的时候应当返回一个新对象，保证前后两个值===的结果为false

**Comment by guohuihot** [comment]
怎么这次修改过以后，连续上传，on-success只执行一次了

**Comment by elfman** [comment]
@guohuihot 这个pr没有修改hook相关的部分啊，能否给个demo？

**Comment by guohuihot** [comment]
哦，应该不是这次修改的问题，还是老问题file-list ，multiple不能共用，我先看看回头弄个demo

**Comment by luowei1991** [comment]
file-list ，multiple不能共用的问题解决了吗。急呀！

**Pull request merged**
