### PR TITLE
date-time-picker: fix incorrect date on time pick

### PR DESCRIPTION
**Pull request by wacky6**
Regression introduced during 2.0 refactor. Quite surprised that it took 7 months for someone to spot this bug. 😂

`modifyWithDefaultTime` changed to `modifyWithTimeString` to reflect what it does.

### CODE REVIEW

**Comment by Leopoldthecoder** [comment]
Actually I think what #11450 meant was

untitled1

**Comment by wacky6** [comment]
Updated, I missed the `confirm()` bit. It should work correctly now.
https://jsfiddle.net/4frk3fmd/

---

Recommend CI/bot reply to include url of compiled element-ui bundle that can be used to write jsfiddle happily. It might be troublesome if amendments are made (thus changing bundle's hash -> http 404). Right now, I'm happy with my [js-bin](https://github.com/wacky6/js-bin) hack. :D

**Comment by Leopoldthecoder** [comment]
It seems the compiled `element-ui.[hash].js` for netlify / official website cannot be used in jsfiddle. @jikkai could you verify this?

**Comment by zaoyu63** [comment]
this.value 如果不是日期类型，是个字符串， modifyTime方法就会报错!!!
This value if not date type, is a string, modifyTime method will be an error!!!

**Comment by jayzch** [comment]
重构有问题啊！！问题同上，整个系统挂了。

**Comment by wacky6** [comment]
https://github.com/ElemeFE/element/issues/11621#issuecomment-398272178

**Pull request merged**
