### PR TITLE
[table] 性能优化,使用dom 操作切换hover 样式，减少 mousehover 频繁触发  this.store.commit…

### PR DESCRIPTION
**Pull request by nailfar**
…('setHoverRow', index)造成的表格重新render; 使用throttle减少resize 造成的表格重新布局函数doLayout的触发频率,在表格不可见时无需对表格进行重新doLayout;

Please make sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by iamkun** [comment]
Please provide a benchmark or demo

**Comment by SimonaliaChen** [comment]
没用的setHoverRow等处理事件还没删除哦~

**Comment by ziyoung** [comment]
请提供性能测试数据。

**Comment by ziyoung** [comment]
fixed in #15709

**Comment by nailfar** [comment]
想请教下性能测试数据怎么来，用什么工具，生成什么样的报告，报告格式什么样

**Pull request closed without merging**
