### PR TITLE
quickstart: updating document

### PR DESCRIPTION
**Pull request by suweiteng**
updating document quickstart.md. add ‘Notification’ to Component list.

Please make sure these boxes are checked before submitting your PR, thank you!

* [ ] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md)).
* [ ] Make sure you are merging your commits to `dev` branch.
* [ ] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by Leopoldthecoder** [comment]
Duplicate of #5756

**Comment by suweiteng** [comment]
@Leopoldthecoder 
5756 is  zh-CN , 5757 is en-US

**Comment by Leopoldthecoder** [comment]
Oh, sorry. Merging it now.

**Comment by suweiteng** [comment]
cool！

**Pull request merged**
