### PR TITLE
Table: height accepts more units

### LINKED ISSUE #15806: 2.9.1 table components set height to 100% cause some problem
### Element UI version
2.9.1

### OS/Browsers version
mac/chrome

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/ykl/pen/eaQWpR

### Steps to reproduce
set height to 100% in component el-table
open any browser to see the height become 100px
surprise~

### What is Expected?
the actual height become 100%

### What is actually happening?
the actual height become 100px

### LINKED ISSUE #15858: The Height Attribute Problem of [Bug Report] Table
### Element UI version
2.9.1

### OS/Browsers version
windos10/Google Chrome版本 73.0.3683.86（正式版本） （64 位）

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/aime1991/pen/arXpyP

### Steps to reproduce
<el-table
    :data="tableData"
    border
    height="100%"
    style="width: 100%">
其中height设置为100%，但是在实际的页面中显示的是100px。
在版本2.5.4中这样设置，在实际页面中显示的是100%。

### What is Expected?
height设置为100%时，在实际页面中应该是 100%；和版本2.5.4保持一直。

### What is actually happening?
height设置为100%时，在实际页面中是100px

### LINKED ISSUE #16064: [Bug Report] Table height changes to 100px (en: el-table forced the style height 100px)
### Element UI version
0.1.0

### OS/Browsers version
Google Chrome

### Vue version
2.5.20

### Reproduction Link
http://giser.tk/2019/06/14/38442.html

### Steps to reproduce
之前使用2.8.1版本正常，更新版本2.9.1后，

### What is Expected?
表格高度自适应

### What is actually happening?
表格高度都强制设为100px

### PR DESCRIPTION
**Pull request by ziyoung**
Please make sure these boxes are checked before submitting your PR, thank you!

* [ ] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [ ] Make sure you are merging your commits to `dev` branch.
* [ ] Add some descriptions and refer relative issues for you PR.
- Closes #15806
- Closes #15858
- Closes #16064

related pr #15830

### CODE REVIEW

**Comment by ziyoung** [comment]
删除了我认为多余的部分代码，有待增加更多的测试。

**Comment by Zkangmas** [comment]
image
image
请问下为什么要删除 data 变化时 调用 doLayout的逻辑啊？没有这段逻辑在表格有垂直滚动条的情况下，没法设置表头gutter的宽度。

**Comment by Zkangmas** [comment]
垂直滚动在同时有条和水平滚动条的时候会出现上述情况

**Comment by ziyoung** [comment]
提 issue 吧，补充一个 demo。

**Pull request merged**
