### PR TITLE
i18n: #14359 - Added Croatian (hr) locale 

### PR DESCRIPTION
**Pull request by danijelh**
Please make sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by ziyoung** [comment]
@danijelh thanks for your pr. You also need update `i18n.md` in docs.

**Comment by danijelh** [comment]
@ziyoung Yes of course. Sorry. I have pushed also doc changes.

**Comment by ziyoung** [comment]
image
问题依旧没解决。等想好之后再提吧。

**Comment by ziyoung** [comment]
@danijelh sorry for my fault.

**Comment by ziyoung** [comment]
@danijelh This branch has conflicts and please pull the latest code.

**Pull request merged**
