### PR TITLE
Update infiniteScroll.d.ts

### PR DESCRIPTION
**Pull request by notcold**
modify the export name

Please make sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by VirensCn** [comment]
have bug.....
[element-ui.d.ts](https://github.com/ElemeFE/element/blob/dev/types/element-ui.d.ts)

**Comment by troy351** [comment]
Still get error from `element-ui.d.ts` line 331
`Cannot extend an interface 'ElInfiniteScroll'. Did you mean 'implements'?`

**Comment by troy351** [comment]
@iamkun This PR does not actually solved the problem

**Comment by iamkun** [comment]
@troy351 Some detail, please?

**Comment by troy351** [comment]
As I said above, 
image
`InfiniteScroll` is a Directive not a Component

**Comment by iamkun** [comment]
@tahq69 fix in #15794

**Pull request merged**
