### PR TITLE
Drawer: Added component

### PR DESCRIPTION
**Pull request by sunhaoxiang**
* [x] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer relative issues for you PR.

A Drawer is a panel that is typically overlaid on top of a page and slides in from the side. It contains a set of information or actions. Since that user can interact with the Drawer without leaving the current page, tasks can be achieved more efficient within the same context.

[issue #12610](https://github.com/ElemeFE/element/issues/12610)
[issue #12724](https://github.com/ElemeFE/element/issues/12724)

### CODE REVIEW

**Comment by ziyoung** [comment]
@sunhaoxiang Thanks for your contribution. 
We will develop a new component until the designer provides design drafts. Now, we have no plan to add this component. I think you can add this component to [awesome-element](https://github.com/ElementUI/awesome-element).

**Comment by oller** [comment]
This seems like a great addition and a very good PR. Excellent work @sunhaoxiang . It is a shame it's gone to waste, it would be great if it were released somewhere even if element ui aren't going to include it (iView has a drawer component).

Any chance of releasing it via npm and registered it with awesome-element @sunhaoxiang?

**Comment by thearabbit** [comment]
I need this `Drawer Component` too.
+1, Where could I try?

**Comment by thearabbit** [comment]
Could I copy this component source into local project?

**Comment by sunhaoxiang** [comment]
@thearabbit Yes, of course.

**Comment by thearabbit** [comment]
could you example, how to?

**Comment by sunhaoxiang** [comment]
https://github.com/sunhaoxiang/element/tree/dev/packages/drawer

**Comment by thearabbit** [comment]
Yes, i saw this.
But I don't know to config in local (how to use)?

**Comment by sunhaoxiang** [comment]
https://github.com/sunhaoxiang/element/blob/dev/packages/theme-chalk/src/drawer.scss
And the SCSS file.

**Comment by sunhaoxiang** [comment]
This component also based on Element.So you can take a look at which Element methods the component calls and copy this methods to your project.

**Comment by thearabbit** [comment]
My structure (I base on `Meteor + Vue`)
```
// main.js
import Vue from 'vue'

import ElementUI from 'element-ui'
import 'element-ui/lib/theme-chalk/index.css'
import locale from 'element-ui/lib/locale/lang/en'
Vue.use(ElementUI, { locale, size: 'small' })
....
import ElDrawer from '/imports/client/plugins/drawer'
import '/imports/client/plugins/drawer/drawer.scss'
Vue.use(ElDrawer)
```
```js
// imports/client/plugins/drawer
  index.js
  drawer.scss
  src/
    component.vue
```
But don't work

**Comment by thearabbit** [comment]
I try custom to local plugin
```js
// componenet
import Popup from 'element-ui/src/utils/popup'
import Migrating from 'element-ui/src/mixins/migrating'
import emitter from 'element-ui/src/mixins/emitter'
export default {
  name: 'ElDrawer',
..............
---------------------------
// drawer.scss
@import '~element-ui/packages/theme-chalk/src/mixins/mixins';
@import '~element-ui/packages/theme-chalk/src/mixins/utils';
@import '~element-ui/packages/theme-chalk/src/common/var';
@import '~element-ui/packages/theme-chalk/src/common/popup';

@include b(drawer) {
  position: fixed;
  margin: 0;
  background: $--color-white;
  box-shadow: $--drawer-box-shadow;
  box-sizing: border-box;
  width: 50%;
  height: 100%;
-------------------
// drawer-plugin.js
import ElDrawer from './drawer/index.js'

const Drawer = {
  install(Vue, options) {
    Vue.component('el-drawer', ElDrawer)
  },
}

export default Drawer
```
Still don't work,

**Comment by thearabbit** [comment]
Could you push this to `Element UI Plugin`?

**Comment by thearabbit** [comment]
Have any solve?

**Pull request closed without merging**
