### PR TITLE
Tabs: fix issue 14601 bug

### LINKED ISSUE #14601: The [Bug Report] tab el-tabs component uses slot custom tag content. The attribute values of element binding in slot scope can not be changed responsively in the new version (2.6.x). It is possible in the old version 2.4.x.
### Element UI version
2.6.1

### OS/Browsers version
谷歌

### Vue version
2.6.8

### Reproduction Link
[https://jsfiddle.net/](https://jsfiddle.net/)

### Steps to reproduce
重现具体链接:http://jsrun.net/PwXKp/edit
步骤:点击button按钮改变属性值,看用slot自定义的标签内容是否随属性值的变化而响应式改变

### What is Expected?
自定义标签内容随属性值变化而响应式改变

### What is actually happening?
没有响应式改变

### LINKED ISSUE #14712: [Bug Report] [ElTabs 2.5.x 2.6.x]: 在ElTabPane的label slot中的视图不响应数据变化
### Element UI version
2.6.0

### OS/Browsers version
版本 72.0.3626.81（正式版本） （64 位）

### Vue version
2.5.17

### Reproduction Link
[https://jsfiddle.net/m91yuzp4/1/](https://jsfiddle.net/m91yuzp4/1/)

### Steps to reproduce
理论上，`setTimeout`回调时，视图应该响应数据的变化，但是在`2.5.x`和`2.6.x`的版本下，视图没有更新。

但是`2.4.11`是没问题的，看了下`2.5.0`的git log，关于el-tabs的改动应该不会影响数据响应，自己也很纠结到底哪里出问题了，所以辛苦大佬们看一下~

### What is Expected?
视图应该响应数据变化

### What is actually happening?
2.5.x和2.6.x版本下，视图没有响应数据变化

### PR DESCRIPTION
**Pull request by lucyhao**
Please make sure these boxes are checked before submitting your PR, thank you!

closes #14601
closes #14712

* [ ] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [ ] Make sure you are merging your commits to `dev` branch.
* [ ] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by ziyoung** [comment]
一个类似的pr #14496

**Comment by ziyoung** [comment]
@lucyhao 代码冲突了，更新一下代码。

**Comment by ganl** [comment]
+1

**Comment by iamkun** [comment]
Conflict

**Comment by island205** [comment]
I'll close this PR since it's been a while since it's been opened. Feel free to reopen if you have updates on this

**Pull request closed without merging**
