### PR TITLE
Changelog: update for 2.1.0 (#9581)

### PR DESCRIPTION
**Pull request by Gonzalo2310**
Please make sure these boxes are checked before submitting your PR, thank you!

* [ ] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md)).
* [ ] Make sure you are merging your commits to `dev` branch.
* [ ] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by Gonzalo2310** [comment]
Changes.
Changelog.es.md (Updating information)
Translate and update info: form.md / date-picker.md / table.md / cascader.md / notification.md

I think it's all up to date but I'm not 100% sure. There were quite a few changes in January that I didn't know.
As always, thank you.

**Comment by Leopoldthecoder** [comment]
Thanks, you are so efficient!

There are some more files need to be translated:
- [dropdown.md](https://github.com/ElemeFE/element/commit/f274f3e3d9db0fcd024bc8f3800ff6ba70817f77#diff-1d5cebb78a8b45c3c263d52c5cb495a6R333)
- The three pickers: https://github.com/ElemeFE/element/commit/2fa6935e58bc494db0d4b8b0a5ee4bb378045e0b

In https://github.com/ElemeFE/element/commit/2fa6935e58bc494db0d4b8b0a5ee4bb378045e0b you can see 6 files are changed: 3 for Chinese doc and 3 for English doc. It's my fault forgetting to paste the updates to the Spanish doc. Could you help update them?

**Comment by Gonzalo2310** [comment]
I'll get right on it.

And you're not guilty of any forgetting. This part at least is teamwork. 👍

**Comment by Gonzalo2310** [comment]
I think we got him. If not, let me know.
A pleasure to collaborate as always.

**Comment by Leopoldthecoder** [comment]
Thanks! I'll deploy the docs now.

**Comment by Gonzalo2310** [comment]
Thanks for fixing the urls.

**Pull request merged**
