### PR TITLE
Input: Add mask support(#10377)

### PR DESCRIPTION
**Pull request by elfman**
将[jQuery-Mask-Plugin](http://igorescobar.github.io/jQuery-Mask-Plugin/)的代码移了过来，为`Input`添加一样的功能，感觉这个插件的功能还挺不错的

### CODE REVIEW

**Comment by BryceBarbara** [comment]
Is there any news on the status of this pull request? I've been needing the element input to have built-in masking support for some time. 

There are hack-y options that involve intercepting/overwriting the component's methods but I see those as time-bombs just waiting for a breaking change.

**Comment by BryceBarbara** [comment]
Looking closer, the watch on the `mask` prop should be a deep watch.

**Comment by island205** [comment]
We will merge this feature to our inner project called Element Plus

**Comment by BryceBarbara** [comment]
@island205 Hopefully that isn't some premium/paid version of element-ui. But if not, I'm glad to see this is getting picked up and incorporated!

**Comment by island205** [comment]
@BryceBarbara It's not, it will open source someday.

**Pull request closed without merging**
