### PR TITLE
优化: 让input组件支持更多vue v-on事件

### PR DESCRIPTION
**Pull request by vok123**
Please make sure these boxes are checked before submitting your PR, thank you!
过computed自动合并事件, 让input组件支持更多vue v-on事件. 
例如支持: 键盘(@mouseup...), 鼠标相关事件
* [ ] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [ ] Make sure you are merging your commits to `dev` branch.
* [ ] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by ziyoung** [comment]
更为复杂的场景使用 `.native` 修饰符。

**Comment by vok123** [comment]
> 更为复杂的场景使用 `.native` 修饰符。
只是感觉直接使用更方便而已

**Comment by vok123** [comment]
直接使用更为方便些

**Comment by iamkun** [comment]
I'll close this issue since it's been a while since it's been opened. Feel free to reopen if you have updates on this

**Pull request closed without merging**
