### PR TITLE
chore: make it sass compatible

### PR DESCRIPTION
**Pull request by KazuAlex**
Please make sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer relative issues for you PR.

This PR is a rework of https://github.com/ElemeFE/element/pull/21019 that make theme-chalk node-sass **and** sass compatible without removing current node-sass

### CODE REVIEW

**Comment by KazuAlex** [comment]
Up!

**Comment by KazuAlex** [comment]
What's up ?

**Comment by jdinartejesus** [comment]
I would love to see this being merged, @KazuAlex. Anything we can do to push this?

**Review by jdinartejesus — APPROVED** [review]

**Comment by KazuAlex** [comment]
Ni idea. I just do the work but element team seams to have abandoned this repo ¯\_(ツ)_/¯

**Comment by ryougifujino** [comment]
This should be merged in order to make this repo compatible with latest node.

**Comment by KazuAlex** [comment]
I'll try to ping people...
@xinguanhua @cs1707 😘

**Comment by xinguanhua** [comment]
related update in v2.15.7 occurred some compatibility problems, so reversed in v2.15.8, will be fixed in v2.16.0 soon

**Pull request closed without merging**
