### PR TITLE
Input/Select: Hide clearable icon when field is null

### PR DESCRIPTION
**Pull request by liam-potter**
Please make sure these boxes are checked before submitting your PR, thank you!

* [X] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md)).
* [X] Make sure you are merging your commits to `dev` branch.
* [X] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by liam-potter** [comment]
Not sure why Travis has failed on a DatePicker test - I have not touched the DatePicker with this pull request, only Input and Select.

**Comment by wacky6** [comment]
I suspect it's a flaky test. Try restart the build, then it will probably be fine.

**Comment by wacky6** [comment]
Also, please write unit tests for your proposed change.
Otherwise it might be changed / broken by  others.

**Comment by liam-potter** [comment]
I have added tests to my local copy but I am unable to run them, I get the following error:
```bash
$ npm run test

> element-ui@2.2.0 test D:\Projects\GitHub\element
> npm run lint && npm run build:theme && cross-env CI_ENV=/dev/ karma start test/unit/karma.conf.js --single-run


> element-ui@2.2.0 lint D:\Projects\GitHub\element
> eslint src/**/* test/**/* packages/**/* build/**/* --quiet


D:\Projects\GitHub\element\packages\theme-chalk\src\fonts\element-icons.ttf
  1:1  error  Parsing error: Unexpected character ' '

D:\Projects\GitHub\element\packages\theme-chalk\src\fonts\element-icons.woff
  1:5  error  Parsing error: Unexpected character ' '

✖ 2 problems (2 errors, 0 warnings)
```

**Comment by Leopoldthecoder** [comment]
If you're seeing these eslint errors, please remove your `node_modules` folder and reinstall dependencies **using yarn**.

**Comment by liam-potter** [comment]
@Leopoldthecoder I used Yarn (1.5.1) when initially installing dependencies. I have tried removing `node_modules` and reinstalling the dependencies again with `yarn` but the same error persists.

**Comment by wacky6** [comment]
@liam-potter 
Might be caused by local / global eslint version difference. Right now, element's package.json uses global eslint.

Try edit package.json's `scripts.lint` to `./node_modules/.bin/eslint src/**/* test/**/* packages/**/* build/**/* --quiet`.

**Comment by liam-potter** [comment]
There is indeed a difference in my local/global versions of eslint. Global is `4.18.1` and local is `4.14.0`. I have tried your suggestion of altering the `scripts.lint` in `package.json` but the same error persists.

One other curious note is that after running `yarn` to reinstall dependencies I noticed that `yarn.lock` gets updated with an additional reference to a newer version of `eslint-elemefe` whilst keeping the existing older reference:

```bash
eslint-config-elemefe@*:
  version "0.3.0"
  resolved "https://registry.yarnpkg.com/eslint-config-elemefe/-/eslint-config-elemefe-0.3.0.tgz#6f06cd6a8c6949bf58fa7fe2d4b4a4fde89bf008"

eslint-config-elemefe@0.1.1:
  version "0.1.1"
  resolved "https://registry.yarnpkg.com/eslint-config-elemefe/-/eslint-config-elemefe-0.1.1.tgz#5a1664ce3f7d91f68528b508d040044ae6c10aa3"
```

Not sure if this could perhaps be related?

I believe I have now fixed the test for the `Select` component but I am reluctant to push it up again (having already committed the test and changes 3 times) until I have tested it working locally so that I do not keep getting Travis errors or pollute the commit history.

**Comment by liam-potter** [comment]
Closing due to inactivity - let me know if you would like me to re-open this but I will need some assistance with resolving https://github.com/ElemeFE/element/pull/9921#issuecomment-369292725.

**Pull request closed without merging**
