### PR TITLE
Tabs: fix a 'activeName' attribute init bug

### PR DESCRIPTION
**Pull request by Kingwl**
Please makes sure these boxes are checked before submitting your PR, thank you!

* [ ] Make sure you follow Element's [Contributing Guide](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.md).
* [ ] Rebase before creating a PR to keep commit history clear.
* [ ] Add some descriptions and refer relative issues for you PR.

// 再来一次

### CODE REVIEW

**Comment by zapline** [comment]
It's very helpful to me.

**Comment by MaxTan** [comment]
It's very helpful to me.

**Comment by AngryPowman** [comment]
It's very helpful to me.

**Comment by DevilNeverCry** [comment]
It's very helpful to me.

**Pull request merged**
