### PR TITLE
fixed hidden dom element loading bug

### PR DESCRIPTION
**Pull request by xiongzixiao**
When two elements of one parent element are bound to the v-loading.body property at the same time, if one of the elements is in the hidden state, then there will be a bug occur when the other child element is loading

### CODE REVIEW

**Comment by Leopoldthecoder** [comment]
Could you write a demo to reproduce the bug?

**Comment by xiongzixiao** [comment]
```
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <!-- 引入样式 -->
  <link rel="stylesheet" href="https://unpkg.com/element-ui/lib/theme-default/index.css">
</head>
<body>
  <div id="app">
    <el-tabs v-model="activeName" @tab-click="handleClick">
        <el-tab-pane label="用户管理" name="first" v-loading.body="loading">用户管理</el-tab-pane>
      <el-tab-pane label="配置管理" name="second" v-loading.body="loading">配置管理</el-tab-pane>
    </el-tabs>
  </div>
</body>
  <!-- 先引入 Vue -->
  <script src="https://unpkg.com/vue/dist/vue.js"></script>
  <!-- 引入组件库 -->
  <script src="https://unpkg.com/element-ui/lib/index.js"></script>
  <script>
    new Vue({
      el: '#app',
      data: function() {
        return {
          activeName: 'second',
          loading: true
        }
      }
    })
  </script>
</html>

```

**Comment by xiongzixiao** [comment]
this is the demo to reproduce the bug

**Pull request merged**
