### PR TITLE
[Dropdown Item] Add icon prop to dropdown-item

### PR DESCRIPTION
**Pull request by gabrielboliveira**
Please make sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer relative issues for you PR.

This is a new feature to add a new prop to Dropdown Item. It's now possible to add a icon 🎉 

image

### CODE REVIEW

**Comment by ziyoung** [comment]
@gabrielboliveira it's awesome.👍Now, the French doc has been added. Fetch the latest code and update the French doc. Don't worry about translation.

**Comment by gabrielboliveira** [comment]
@ziyoung done!

**Comment by gabrielboliveira** [comment]
Just realized I missed the Typescript definition.. Should I add it?

**Comment by ziyoung** [comment]
@gabrielboliveira yes, you are right. I will merge this pr after you add it.

**Comment by gabrielboliveira** [comment]
@ziyoung Added. Now it looks good to go 👍

**Pull request merged**
