### PR TITLE
InfiniteScroll: fix trigger when component is invisable

### LINKED ISSUE #16673: [Bug Report] InfiniteScroll always trigger when component hidden
### Element UI version
2.10.1

### OS/Browsers version
Chrome

### Vue version
2.1.10

### Reproduction Link
https://codepen.io/a631807682/pen/aedzBm?editors=1011

### Steps to reproduce
loading always true and console alway print `load more`

### What is Expected?
dose not trigger when component hidden

### What is actually happening?
 always trigger when component hidden

### PR DESCRIPTION
**Pull request by a631807682**
Please make sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer relative issues for you PR.

Close #16673
Ref PR #16681

### CODE REVIEW

**Comment by a631807682** [comment]
从pr #16681 修改而来，那个大佬消失了。

**Comment by iamkun** [comment]
Please avoid using `IntersectionObserver ` to support Internet Explorer 10+.

**Comment by a631807682** [comment]
> Please avoid using `IntersectionObserver ` to support Internet Explorer 10+.

Thanks for review, i using `timer` instead.

**Comment by iamkun** [comment]
可以看下我关联的 pr 感觉可以直接跳过对隐藏元素的处理就可以了

**Pull request closed without merging**
