### PR TITLE
Form: fix style when label-width is auto

### PR DESCRIPTION
**Pull request by ziyoung**
Please make sure these boxes are checked before submitting your PR, thank you!

* [ ] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [ ] Make sure you are merging your commits to `dev` branch.
* [ ] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by de1ck** [comment]
valdator required: true red tag is miss

**Comment by ziyoung** [comment]
> valdator required: true red tag is miss

Yes. I will fix it soon.

**Comment by iTaster** [comment]
The problem has not been fixed

 error  in ./~/element-ui/packages/form/src/label-wrap.vue

Syntax Error: Unexpected token (21:8)

  19 |       }
  20 |       return (
> 21 |         <div class="el-form-item__label-wrap" style={style}>
     |         ^
  22 |         { slots }
  23 |         </div>)
  24 |     } else {

fix

  19 |       }
  20 |       return (
> 21 |         `<div class="el-form-item__label-wrap" style={style}>
     |         ^
  22 |         { slots }
  23 |         </div>)`
  24 |     } else {

**Comment by ziyoung** [comment]
@iTaster can't reproduce. Please provide a demo.

**Pull request merged**
