### PR TITLE
Cascader:fix same node value for different level  not render correct bug

### PR DESCRIPTION
**Pull request by qingdengyue**
Please make sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by qingdengyue** [comment]
#16085

**Comment by zhijunw** [comment]
请问 你这边的解决  是下个版本更新就完事了吗   我现在是2.10  也还是有类似问题

**Comment by island205** [comment]
@qingdengyue Please resolve the conflicts

**Comment by island205** [comment]
Duplicate of #16465

**Comment by island205** [comment]
fixed in #15935

**Pull request closed without merging**
