### PR TITLE
Dropdown: Dropdown supports disabled

### LINKED ISSUE #11823: [Feature Request] Add 'disabled' option to el-dropdown split-button buttons
### Existing Component
Yes

### Component Name
el-dropdown

### Description
The option items can be disabled with ```disabled``` flag. But the button of ```split-button``` option didn't support the ```disabled``` flag. Disable the button is useful at some cases.

### PR DESCRIPTION
**Pull request by ziyoung**
Closes #11823

### CODE REVIEW

**Comment by Shouhua** [comment]
请问这个功能在那个版本发布？

**Comment by pengliheng** [comment]
用不了啊, 都快 2020 了.

**Comment by smg99** [comment]
Can someone please merge this?

**Comment by debovema** [comment]
Can someone please rebase & merge this?

**Pull request closed without merging**
