### PR TITLE
Update spanish documentation

### PR DESCRIPTION
**Pull request by Gonzalo2310**
Please make sure these boxes are checked before submitting your PR, thank you!

* [ ] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md)).
* [ ] Make sure you are merging your commits to `dev` branch.
* [ ] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by Gonzalo2310** [comment]
Awesome preview. Great idea

**Comment by Leopoldthecoder** [comment]
Thanks!

**Comment by Gonzalo2310** [comment]
Problems?

**Comment by Leopoldthecoder** [comment]
No, I accidentally clicked that button😂. This PR is fine.

**Comment by Gonzalo2310** [comment]
You want me to have a heart attack.

**Comment by Leopoldthecoder** [comment]
So sorry, man🤣

**Comment by Gonzalo2310** [comment]
jajajjajajajajaj
It's a joke......

**Pull request merged**
