### PR TITLE
Table: Add eventListener option passive

### PR DESCRIPTION
**Pull request by akifo**
Please make sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by liril-net** [comment]
What is the purpose to add this property?

**Comment by akifo** [comment]
Chrome's[v63.0.3239.108] console has the following warning

```
[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. 
Consider marking event handler as 'passive' to make the page more responsive. 
See https://www.chromestatus.com/feature/5745543795965952
```

If the event doesn't use preventDefault, we should set `{ passive: true }` for smooth scrolling experience.

**Comment by wuliupo** [comment]
When will this commit be merged into master and release?
@Leopoldthecoder

**Comment by akifo** [comment]
Once merged, but it has been deleted by this commit https://github.com/ElemeFE/element/commit/bbe6e62ee1574a2dc9a9c87a628869e13583ce1f#diff-9cb0575a7b0cf4669671ce0485f25c49

@wuliupo 
You can create new PR.

**Comment by gaberudy** [comment]
@Leopoldthecoder are you able to re-do this commit based on the new changes? I am also hoping to get rid of these Chrome warnings and hopefully see some UI responsiveness improvements

**Pull request merged**
