### PR TITLE
[Select] : add button to select all in multiple case

### PR DESCRIPTION
**Pull request by IneoO**
Please make sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer relative issues for you PR.

I add a button to select all / deselect all elements in select option. 
I would like some help to translate in every language defaults labels buttons.

image

### CODE REVIEW

**Comment by wacky6** [comment]
Why not use checkbox's select all for this kind of scenario (If you expect user to select all in a list). Whether this PR is going to be merged requires further discussion.

If this feature can be accepted after discussion:
* CI failed, please check what's wrong.
* Write tests, or this feature will be broken by someone else.

@Leopoldthecoder

**Comment by IneoO** [comment]
I need it beacause i have many elements it take up less space on the page and it's more friendly.

I fixed CI, chinese woring was missing (but i don't think it's the best translation). 
I wrote a test for this feature.

**Comment by Leopoldthecoder** [comment]
Thanks for contributing.

But IMHO, Select doesn't need such an API natively, since you can already implement this feature: https://jsfiddle.net/leopoldthecuber/5z998pw9/6/ .

**Comment by lionslair** [comment]
+1 for merging this would be a nice feature to have ability to do as a prop. But thank you for the example of how to do this as this Is what I was looking for. Same reasons. Space.

**Comment by xianshenglu** [comment]
+1 But a checkbox might be better.

**Pull request closed without merging**
