### PR TITLE
TimePicker: fix TimePicker style on windows

### PR DESCRIPTION
**Pull request by fisker**
Please make sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer relative issues for you PR.

windows上滚动条的宽度不是15px 导致 timePicker 错位。
time-panel 的蓝色条 32px 高，margin-top 应该是一半，所以改成了-16px

el-time-spinner__wrapper 最大高度也少了2像素 应该 32px * 6 = 192px, 同时这里必须是 content-box，加上可以防止全局设置的影响

### CODE REVIEW

**Comment by Leopoldthecoder** [comment]
请提供出现问题的截图。

**Comment by fisker** [comment]
image

**Comment by fisker** [comment]
do the math

**Comment by fisker** [comment]
@Leopoldthecoder

**Pull request closed without merging**
