### PR TITLE
fix textarea style in form

### PR DESCRIPTION
**Pull request by Leopoldthecoder**
Please makes sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's [Contributing Guide](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.md).
* [x] Rebase before creating a PR to keep commit history clear.
* [x] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by QingWei-Li** [comment]
lgtm 不是要发新版？

**Comment by Leopoldthecoder** [comment]
明天发吧……你看看要不要把你今天打包策略的变化写到 changelog 里

**Comment by QingWei-Li** [comment]
那正好先升级到 rc5 看看那几个问题好了没。。

**Comment by Leopoldthecoder** [comment]
机智

**Pull request merged**
