### PR TITLE
Dialog docs improve

### PR DESCRIPTION
**Pull request by baiyaaaaa**
Please makes sure these boxes are checked before submitting your PR, thank you!

* [ ] Make sure you follow Element's [Contributing Guide](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.md).
* [ ] Rebase before creating a PR to keep commit history clear.
* [ ] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by baiyaaaaa** [comment]
#221

**Comment by Leopoldthecoder** [comment]
😂 这个我想改成 `onOpen` 和 `onClose`，不然感觉容易和前面的混淆。或者你直接改了？

**Comment by baiyaaaaa** [comment]
@Leopoldthecoder 你是说把事件改成回调钩子么？

**Comment by Leopoldthecoder** [comment]
就是改下名字，把[这里](https://github.com/ElemeFE/element/blob/master/packages/dialog/src/component.vue#L74)和[这里](https://github.com/ElemeFE/element/blob/master/packages/dialog/src/component.vue#L79)改成 ` this.$emit('onOpen');` 和 ` this.$emit('onClose');`，否则
image

**Comment by baiyaaaaa** [comment]
恩。。感觉没什么关系，事件命名还是统一比较好，现在事件名都不加 on 前缀

**Comment by Leopoldthecoder** [comment]
哦，好象是，那就这样吧。

**Pull request merged**
