### PR TITLE
From: Complete the form component prop field description

### PR DESCRIPTION
**Pull request by luciy**
完善 form 组件 prop 字段说明：
在项目使用中如果并不需要对input做验证 可能就不会填写prop字段，但是resetFields（重置表单功能）依然需要prop字段，所以需要加以说明。在什么情况下选填，什么情况下必填。

Complete the form component prop field description:
In the project, if you don't need to validate the input, you probably won't fill out the prop field, but the resetFields (reset form function) still needs the prop field, so it needs to be explained. In what circumstances students under what circumstances required.

### CODE REVIEW

**Comment by Leopoldthecoder** [comment]
Thanks for contributing, but please rebase code. Now it can't be merged due to conflicts.

**Comment by luciy** [comment]
@Leopoldthecoder 已经拉取最新代码。

**Comment by Leopoldthecoder** [comment]
@luciy Please resolve conflicts

**Comment by luciy** [comment]
@Leopoldthecoder 已解决

**Pull request merged**
