### PR TITLE
fix: Fix Notification title word break

### LINKED ISSUE #14893: [Bug Report] Notification spacing
### Element UI version
2.7.0

### OS/Browsers version
MacOS 10.13.6 / Chrome 73.0.3683.86

### Vue version
2.6.10

### Reproduction Link
[https://jsfiddle.net/r4qnuxjs/](https://jsfiddle.net/r4qnuxjs/)

### Steps to reproduce
Create a notification with a title long enough to fill the entire top row.

### What is Expected?
There should be an even amount of spacing between the notification content and the close button.

### What is actually happening?
The title runs right into the close button, making it unclear there's an X to click sometimes.

Screen Shot 2019-03-28 at 13 52 32

### PR DESCRIPTION
**Pull request by iamkun**
close #14893
Please make sure these boxes are checked before submitting your PR, thank you!

* [ ] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [ ] Make sure you are merging your commits to `dev` branch.
* [ ] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by breadadams** [comment]
@iamkun, I don't think that this is an appropriate fix. You can't just split words up for **everyone**'s notifications. It looks bad, and I _know_ my client will complain about this.

The correct solution would be to adjust the padding so that the text never reaches the X. I can sort this is if you want. Please re-open my original issue.

**Comment by iamkun** [comment]
@breadadams agreed

**Comment by breadadams** [comment]
Cool @iamkun, it's looking better! However given the right amount of characters the text could still run just against the side of the ✖️ icon:

image

I'd add ~8px of padding-right to `.el-notification__title`, leaving the main notifications padding as is.

**Comment by iamkun** [comment]
I think this 2px fix would be enough for most cases.

**Comment by breadadams** [comment]
Sure thing @iamkun, could be...

I couldn't actually get it to happen with anything in english other than random characters, however a client of mine managed to with a Spanish string. Let's see how the 2px fix works and if necessary I'll open a hotfix 😉

**Comment by breadadams** [comment]
Very good point @wacky6, I'd never tried a notification without a title.

The right padding needs increasing a bit more. From a UI point of view I think it's better with a bigger gap like in the above screenshot, it separates the concerns of the "content" and the "action area" better (imo).

So maybe changing from `28px` → `38px`?

**Comment by iamkun** [comment]
@breadadams @wacky6 Updated based on reviews. 😀

**Pull request merged**
