### PR TITLE
Bugfix jumper value

### PR DESCRIPTION
**Pull request by decadef20**
Please make sure these boxes are checked before submitting your PR, thank you!

* [ ] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md)).
* [ ] Make sure you are merging your commits to `dev` branch.
* [ ] Add some descriptions and refer relative issues for you PR.

fix this issue https://github.com/ElemeFE/element/issues/8401#issuecomment-345899880

### CODE REVIEW

**Comment by Leopoldthecoder** [comment]
Please rebase dev branch.

**Comment by decadef20** [comment]
Please check it again.Thanks.
Sorry about too many useless commit messages. 
BTW,the PR only fixed 1.x version. Maybe 2.x also needs one?

**Comment by Leopoldthecoder** [comment]
Please rebase the 1.x branch. The `Files changed` tab should include only files you updated.

As for 2.x, I can take care of it after this  PR is merged.

**Comment by decadef20** [comment]
Please check it again. Thanks for your patience.

**Comment by LDWX** [comment]
分页组件在数据量比较大的时候随便点几次就会出现问题，组件会来来回回的在刚才点击的页号上跳来跳去，而且不会停止。希望官方能够解决一下。

**Comment by decadef20** [comment]
@LDWX  可以提供复现bug的demo吗？

**Comment by LDWX** [comment]
这个不需要demo，是必现bug，你把数据量调到200万左右然后快速点击几次分页组件就能复现

**Pull request merged**
