### PR TITLE
Tree: using defaultExpandedKeys/defaultExpandAll should triger node-e…

### PR DESCRIPTION
**Pull request by nelsonkuang**
…xpand event (#17549)

Please make sure these boxes are checked before submitting your PR, thank you!

* [ ] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [ ] Make sure you are merging your commits to `dev` branch.
* [ ] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by nelsonkuang** [comment]
Need help!! These failed checks were not commited by me :)

**Comment by a631807682** [comment]
> Need help!! These failed checks were not commited by me :)

open `travis-ci` and restart build.

**Comment by nelsonkuang** [comment]
> > Need help!! These failed checks were not commited by me :)
> 
> open `travis-ci` and restart build.

it works, thx

**Comment by nelsonkuang** [comment]
> 多个 message 且高度不一样的情况 你测过吗 ?

测试过来，没问题

**Comment by nelsonkuang** [comment]
> 例如：[80px, 48px, 60px] 这样三个高度的 message，当 close 80px message 的时候后面两个的 top 应该减 80



> 例如：[80px, 48px, 60px] 这样三个高度的 message，当 close 80px message 的时候后面两个的 top 应该减 80

两个高度的没问题，三个高度的有问题，我再看看，这逻辑有点诡异

**Comment by nelsonkuang** [comment]
> 每次减去的应该是 close message 的 offsetHeight，而不是自身的 offsetHeight

没错，之前没测试好哈，commit得太草率了……:thumbsup:

**Pull request closed without merging**
