### PR TITLE
Picker: Only emit 'change' event when value is changed.

### PR DESCRIPTION
**Pull request by remizovvv**
* [x] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer relative issues for you PR.

[issue#9027](https://github.com/ElemeFE/element/issues/9027)

### CODE REVIEW

**Comment by remizovvv** [comment]
@wacky6 , good idea. I changed the PR.
I was a bit confused, when I made out a issue.
I created a issue #9027, and  the same branch for the pull-request. When I made the pool request, it turned out that my issue#9027 was blocked and offered to create an automatic issue. I created new  issue #9031. But this pull-request just updated. 
Do I need to cancel this pull-request and create a similar request from branch issue#9031?

**Comment by wacky6** [comment]
I think you don't have to recreate one. All the changes you made are here.

**Comment by remizovvv** [comment]
@wacky6, yes, you are right. I changed the PR.

**Comment by wacky6** [comment]
@Leopoldthecoder should merge into master in next patch release

**Comment by remizovvv** [comment]
@wacky6, supper, thanks :)

**Comment by liril-net** [comment]
#9027

**Pull request merged**
