### PR TITLE
Select: fix toggle bug

### PR DESCRIPTION
**Pull request by Kingwl**
Please makes sure these boxes are checked before submitting your PR, thank you!

* [ ] Make sure you follow Element's [Contributing Guide](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.md).
* [ ] Make sure you are merging your commits to `dev` branch.
* [ ] Rebase before creating a PR to keep commit history clear.
* [ ] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by Kingwl** [comment]
#1220

**Comment by Leopoldthecoder** [comment]
感谢贡献，确实解决了 #1220 的问题。

目前 Select 还有一个问题（是[同一个改动](https://github.com/ElemeFE/element/pull/1193/commits/d85ed97b58a724715399e3476cfddb64e29659ec#diff-77681c030d3f0bb43a843a628ce7018cR42)导致的）：下拉菜单打开后，点击输入框无法收起。其实我本地已经修了，不过既然你提了这个 PR，不知道你有没有兴趣一起修了（还是在这个 PR 里）？

**Comment by Kingwl** [comment]
233 我说怎么一开始是click.native 然后pull一下就成了focus。。。。
稍等

**Comment by Kingwl** [comment]
@Leopoldthecoder 
`| click | 点击 Input 内的图标时触发 | event |`
为了不破坏input中click的说明 把响应移到了capture期

**Comment by Kingwl** [comment]
sorry 写错了

**Comment by Leopoldthecoder** [comment]
Hi，这样就不能响应 `focus` 事件了

**Comment by Kingwl** [comment]
抱歉 最近有些事耽搁了 您要不把您的合上去吧

**Comment by Leopoldthecoder** [comment]
好的。
Thanks anyway.

**Pull request closed without merging**
