### PR TITLE
Tabs: Tab order does not update when array is sorted

### PR DESCRIPTION
**Pull request by ChuckFields**
https://github.com/ElemeFE/element/issues/12549

Please make sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by ChuckFields** [comment]
fixes bug: [#12549](https://github.com/ElemeFE/element/issues/12549)

**Comment by ziyoung** [comment]
@ChuckFields After slot of Tabs changes, Tabs component re-renders. But `panes` of TabNav doesn't change, so TabNav doesn't re-render. We have to recalculate `panes` based on the slot's content.

**Comment by ziyoung** [comment]
I find a solution.
```js
const panes = this.$slots.default.filter(({ componentInstance }) => componentInstance && componentInstance.$options.componentName === 'ElTabPane')
  .map(( { componentInstance } ) => componentInstance);

// pass panes to TabNav
const navData = {
  props: {
     // ...
     panes
   }
};

```

**Comment by tangdw** [comment]
@ziyoung 大佬，看下使用 slot="label" 还是不行， 见： [https://jsfiddle.net/qk4c23vw/6/](https://jsfiddle.net/qk4c23vw/6/)

**Comment by ziyoung** [comment]
@tangdw 给 slot 加上一个 key：https://jsfiddle.net/qk4c23vw/7/

**Pull request closed without merging**
