### PR TITLE
Table: headerColumn  disabled

### LINKED ISSUE #15605: [Bug Report] el-table-column use selectable=false
### Element UI version
2.8.2

### OS/Browsers version
windows10/Chrome

### Vue version
2.6.10

All of selectable are this false

Table headers cannot be disabled

### PR DESCRIPTION
**Pull request by yyjjqq94**
Please make sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer relative issues for you PR.
Closes #15605

### CODE REVIEW

**Comment by island205** [comment]
PR without descriptions and refer relative valid issues  will be closed directly.

**Comment by yyjjqq94** [comment]
> PR without descriptions and refer relative valid issues will be closed directly.

update issues

**Comment by yyjjqq94** [comment]
@island205 
update issues

**Comment by island205** [comment]
This issue is nothing serious, I think.

**Pull request closed without merging**
