### PR TITLE
Tooltip: add test

### PR DESCRIPTION
**Pull request by QingWei-Li**
Please makes sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's [Contributing Guide](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.md).
* [x] Rebase before creating a PR to keep commit history clear.
* [x] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by furybean** [comment]
怎么感觉方向啥的都没测试？这个放到 popper 里面测试了吗

**Comment by QingWei-Li** [comment]
哦 好 我加上

**Comment by furybean** [comment]
@QingWei-Li 如果是 popper 的 mixin 提供的，就不需要在这里测试，放到 popper 的 mixin 里面测试就好。

**Comment by QingWei-Li** [comment]
嗯 那我写个 vue-popper 的 unittest

**Pull request merged**
