### PR TITLE
fix: ssr friendly

### PR DESCRIPTION
**Pull request by xxholly32**
Please make sure these boxes are checked before submitting your PR, thank you!

* [ ] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [ ] Make sure you are merging your commits to `dev` branch.
* [ ] Add some descriptions and refer relative issues for you PR.

solve problem:
[vuepress build docs Error](https://github.com/vuejs/vuepress/issues/1328#issuecomment-468943461)

### CODE REVIEW

**Comment by island205** [comment]
@xxholly32 I can't figure out what is the root problem, Would you like to provide more detail?

**Comment by xxholly32** [comment]
@island205 you can see more detail by [vuepress issues](https://github.com/vuejs/vuepress/issues/1328)

**Comment by island205** [comment]
@xxholly32 I have read it, but I can't figure out what is the root problem.

**Comment by xxholly32** [comment]
@island205 it seems correct; ty for your time

**Pull request closed without merging**
