### PR TITLE
CascaderPanel: fix bug in parent node and child node have the same value on lazy load mode

### PR DESCRIPTION
**Pull request by EHfive**
Please make sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer relative issues for you PR.

relative PRs: #15935 #16420

### CODE REVIEW

**Comment by EHfive** [comment]
#15935 使 `Store.prototype.getNodeByValue(value)` 的`value`可以匹配`node.path`获取`Node`解决了父子`node.value`重复问题

#16809 由于传入 `Store.prototype.getNodeByValue(value)` 的value不是路径, 使父子value相同会导致回显失败

**Comment by ziyoung** [comment]
请提供个 demo。

**Comment by EHfive** [comment]
https://codepen.io/anon/pen/gVWGxM?editors=1011

**Comment by EHfive** [comment]
Still in v2.13.2

https://codepen.io/ehfive/pen/NWxZYXm

**Comment by EHfive** [comment]
Still in v2.15.5, https://codepen.io/ehfive/pen/NWxZYXm (same URL as above).

The PR seems can still be applied.  But I am not sure if I got enough energy to following up on the PR.

**Pull request closed without merging**
