### PR TITLE
docs: Update contributing guide

### PR DESCRIPTION
**Pull request by sinchang**
Please make sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer relative issues for you PR.

doc improvement

### CODE REVIEW

**Comment by iamkun** [comment]
Please update the relative docs in other languages

**Comment by sinchang** [comment]
> Please update the relative docs in other languages

checked. the docs in other languages are correct

**Comment by iamkun** [comment]
Please check it again. All the same.

**Comment by sinchang** [comment]
> Please check it again. All the same.

updated. thanks.

**Pull request merged**
