### PR TITLE
Table: Add className property to columns

### PR DESCRIPTION
**Pull request by akirak**
Please makes sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's [Contributing Guide](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.md).
* [x] Rebase before creating a PR to keep commit history clear.
* [x] Add some descriptions and refer relative issues for you PR.

This patch allows you to define `className` property in table columns. This property is documented in [Ant Design](https://ant.design/components/table/) and crucial for colourising columns. Combined with `rowClassName`, `className` allows you to colourize the background of cells satisfying a particular conditions, not entire rows.

### CODE REVIEW

**Comment by Leopoldthecoder** [comment]
Thanks for contributing. Could you please edit Table's docs to reflect this patch? 

https://github.com/ElemeFE/element/blob/master/examples/docs/zh-CN/table.md
https://github.com/ElemeFE/element/blob/master/examples/docs/en-US/table.md

**Comment by QingWei-Li** [comment]
Good job!
Could you please fix the Conflict?

**Comment by akirak** [comment]
It's done. Merge #1027 as well.

**Comment by akirak** [comment]
I'm currently working on conflicts. Please wait. Thanks.

**Comment by akirak** [comment]
I've finished a cleaner version of this PR. Please ignore this PR and merge #1027 instead. Thank you very much.

**Pull request closed without merging**
