### PR TITLE
Transfer: fix height, and margin of last child

### PR DESCRIPTION
**Pull request by zjffun**
Please make sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [ ] Add some descriptions and refer relative issues for you PR.

Fix the style of too long or too high items in the Transfer

See [transfer has long item](https://codepen.io/1010543618/pen/XwyqqN)

### CODE REVIEW

**Comment by WaSheep** [comment]
Please describe more in detail

**Comment by zjffun** [comment]
Using flex center the checkbox in vertical direction and hidden the overflow text.

Change `max-height` and `height` to `min-height` for allow custom components in transfer item.

**Comment by zjffun** [comment]
Also fix the `margin-right` value of last `el-checkbox` in transfer

**Comment by zjffun** [comment]
Before
图片

Fix
图片

**Comment by ziyoung** [comment]
Sorry, we have no plan to support this.

**Pull request closed without merging**
