### PR TITLE
Menu: add support for el-menu-item without index

### LINKED ISSUE #13292: [Feature Request] It should be possible to create el-menu-item without route
### Existing Component
Yes

### Component Name
NavMenu

### Description
Currently, there's no straightforward way to create el-menu-item which will not affect current route in menu.

Good use case: we need to open modal dialog when click menu item WITHOUT changing if current route.

Proposed solution:  allow to omit index parameter of el-menu-item or set it to null, in this case clicking on this item will NOT affect current route. 

I think this is very common use case for navigation menu and element should definitely cover it. 

Please let me know if this use case is accepted for inclusion in el-menu-item functionality and I will try to make PR by myself, as this feature is very important for me. Thank you.

### PR DESCRIPTION
**Pull request by georgyfarniev**
Please make sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer relative issues for you PR.

Closes #13292

### CODE REVIEW

**Comment by ziyoung** [comment]
@georgyfarniev which issue does the pr fix?

**Comment by wacky6** [comment]
@ziyoung  See issue: https://github.com/ElemeFE/element/issues/13292

**Comment by georgyfarniev** [comment]
@ziyoung and team, any updates on this? Lack of this feature makes NavMenu almost useless unfortunately.

**Comment by ziyoung** [comment]
@georgyfarniev please provide a simple demo. I'm not familiar with ElMenu and I will invite others to review your code.

**Comment by georgyfarniev** [comment]
@ziyoung thank you for quick response. Here's an example with feature demonstration: https://jsfiddle.net/sd5uce9y/4/ . It's purpose, for example, to create some menu item which should not affect navigation by design, like opening modal dialog with contact form or dynamically switching the language.

**Comment by KINGGUOKUN** [comment]
> @georgyfarniev please provide a simple demo. I'm not familiar with ElMenu and I will invite others to review your code.
那个，我没法提交新的issue，因为那个重现连接完全没法验证通过，所以直接在这里开了。
问题陈述：表单弹框被压盖。
重现步骤：
1、谷歌打开http://118.24.146.176；
2、点击添加按钮。

PS：为什么提Issue时候提重现连接http://118.24.146.176验证不通过？

**Pull request merged**
