### PR TITLE
Tree: add expand-on-click-node prop.

### LINKED ISSUE #1526: [Tree] 希望增加是否通过点击行来展开节点的选项
el-tree组件，点击父节点的名称（label）会缩展子节点，点击父节点的 > 图标也会缩展。
能不能提供属性，可以关闭 “点击父节点名称缩展”，缩展只能点击 >图标 。

### PR DESCRIPTION
**Pull request by furybean**
Please makes sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's [Contributing Guide](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.md).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Rebase before creating a PR to keep commit history clear.
* [x] Add some descriptions and refer relative issues for you PR.

closed #1526, #1708

### CODE REVIEW

**Comment by Leopoldthecoder** [comment]
冲突了

**Comment by furybean** [comment]
@Leopoldthecoder done.

**Comment by fewiki** [comment]
请问这个问题解决了么，我看现在还是点击 节点内容，也展开了子节点

**Comment by SweetJamie** [comment]
expand-on-click-node这属性加了好像没有用 点击内容还是会展开子节点

**Pull request merged**
