### PR TITLE
fix document style bug

### PR DESCRIPTION
**Pull request by liuchuzhang**
Please make sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by ziyoung** [comment]
@liuchuzhang 看起来没问题。补充一下法语文档的更新。

**Comment by liuchuzhang** [comment]
@ziyoung 法语有的，你再看一下。

**Comment by ziyoung** [comment]
@liuchuzhang 我指的是这个文件 `/docs/fr-FR/pagination.md`。你拉一下最新的代码就可以看到了😄。

**Comment by ziyoung** [comment]
@liuchuzhang 拉代码时可以加个 --rebase，pr 里有多余的 commit。

**Comment by liuchuzhang** [comment]
@ziyoung 这西班牙语我把它当成法语了😂
image

**Pull request merged**
