### PR TITLE
DatePicker: in week mode set value to first day of week when user click on cell

### PR DESCRIPTION
**Pull request by elfman**
fix issue #6754

### CODE REVIEW

**Comment by wacky6** [comment]
This is a breaking change, and should be merged into `next`.

**Comment by wacky6** [comment]
Also, in ISO-8601, first day of week is Monday.

Given the current default date-table starts a week from Sunday. After this fix, the component will emit Sunday's date. I doubt if this behavior is what the user really wants.

**Comment by elfman** [comment]
@wacky6 The thing you doubt about should be another case.
Setting the default value of `firstDayOfWeek` to `1` can make `DatePicker` behave as ISO-8601

**Comment by wacky6** [comment]
Setting `firstDayOfWeek = 1` will change the date-table layout, But the user may want to have Sunday to be displayed as the first day, and have the value to start from Monday.

**Comment by elfman** [comment]
@liwenda122 能否说一下哪个地方还有问题？

**Comment by island205** [comment]
Any update?

**Comment by wacky6** [comment]
IMO, week picker should eventually emit a date range. i.e. ['2018-02-03', '2018-02-09'].

Current behavior emits a single date to represent the entire week.

---

This pr breaks current default behavior, which is to have Sunday as the first day on date-table, and emit Monday as component's value.

**Pull request closed without merging**
