### PR TITLE
Input-number: add readonly attribute

### PR DESCRIPTION
**Pull request by asmyshlyaev177**
Please make sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by asmyshlyaev177** [comment]
@Leopoldthecoder  If need to disable control buttons and input area have attribute 'disabled'
Whole point is ability to deny edit input field from keyboard.
Because when user can type non digit symbols or remove value when "min" attribute used it is look strange.

**Comment by Leopoldthecoder** [comment]
Actually `readonly` means you cannot edit the value at all. Look how native input works: https://jsfiddle.net/2otvjrz8/ . With `readonly`, the control buttons are hidden.

**Comment by asmyshlyaev177** [comment]
Hm, i see, maybe just rename attribute, input-readonly, only-controls or input disabled?

**Comment by Leopoldthecoder** [comment]
Then I suggest you manipulate DOM directly: https://jsfiddle.net/jwmyb8ek/ , as this doesn't seem to be a common use case.

**Pull request closed without merging**
