### PR TITLE
return more info from form.validate

### PR DESCRIPTION
**Pull request by xifeiwu**
Please make sure these boxes are checked before submitting your PR, thank you!

* [ ] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [ ] Make sure you are merging your commits to `dev` branch.
* [ ] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by xifeiwu** [comment]
return errorList from form.validate.
compare to invalidFields(object), errorList(array) has a sequence, which is very useful in some condition

**Comment by iamkun** [comment]
Issues without a valid reproduction link will be closed directly.

**Comment by xifeiwu** [comment]
> Issues without a valid reproduction link will be closed directly.

@iamkun ,how should I fix it? (and this is a pr not issue.)

**Comment by iamkun** [comment]
It's better to open an issue as a feature request, before submitting this PR.

**Pull request closed without merging**
