### PR TITLE
DatePicker: fix, add test for unwanted 'input' event emission

### PR DESCRIPTION
**Pull request by wacky6**
Fixes issue: https://github.com/ElemeFE/element/issues/4624

Please make sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer relative issues for you PR.

#### 做了什么
修复Issue：https://github.com/ElemeFE/element/issues/4624
pick事件中，如果pick的值与当前值相等，不发射input

修改后的行为参照了原生`<Select>`，仅在选定的值发生变化时才发射input事件：https://jsfiddle.net/wacky6/a7ffgjdt/

增加了以上行为相关的测试代码

#### Demo
https://jsfiddle.net/wacky6/wya53tm9/2/

#### Issue原因
`type=range`时，它的数据为数组，发射 input 事件中的新建的数组与原数组必然不全等（`===`），触发了watch。
但`type=range`时，它的数据为Date对象，但不会发生Issue所述现象，尚未进一步挖掘原因。

推测 Vue 的 Watcher 有 Date 相关逻辑？

### CODE REVIEW

**Comment by lry210** [comment]
When will it be updated?

**Comment by lry210** [comment]
When will it be updated?

**Comment by wacky6** [comment]
@Leopoldthecoder

**Comment by Leopoldthecoder** [comment]
@QingWei-Li

**Comment by wacky6** [comment]
Do NOT merge! Cleaning up commits! 
Will reopen when complete.

**Comment by wacky6** [comment]
new PR: https://github.com/ElemeFE/element/pull/4837
刚才 push dev 把 commit 搞乱了 😂

@Leopoldthecoder @QingWei-Li @lry210

**Pull request closed without merging**
