### PR TITLE
Upload: add emit onSuccess and Lint Fix

### PR DESCRIPTION
**Pull request by kavalcante**
Please make sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer relative issues for you PR.

Hello, I need to create a function that receive more arguments than the :on-success. For that, I create a simple $emit('success'), with all arguments from a normal :on-success. That way I can handle with a custom function.

Also, I fix a Lint error when I try build dist folder.

Hope you guys accept.

### CODE REVIEW

**Comment by kavalcante** [comment]
Weird, in my terminal when I tried to build, shows lint error. But Travis shows the fix that I made is wrong.

**Comment by kavalcante** [comment]
I've decided to add the emits for OnRemove, OnChange, OnProgress too.

**Comment by Leopoldthecoder** [comment]
> I need to create a function that receive more arguments than the :on-success.

Could you provide more details about this? A demo would be great.

**Comment by kavalcante** [comment]
So, we use Element here at @Cotabox, in part of the application we need to render a form dynamically. The form has this structure: 

```js
items: [
  {
    name: '',
    category: '',
    quantity: 1,
    unit: '',
    comments: '',
    attachments: [],
    fields: [],
  },
],
```

In each "item", can have multiple attachments. The way how Upload component was built, not being reactive on fileList and also executing the onSuccess inside the component (and not emitting and event), don't give me a way to update the fileList correct (of the correct item).

With that solution, I just emit a event with the same value, so I can do this:

```html
<div v-for="item in items">
  <upload
    drag
    name="document"
    :action="UPLOAD_URL"
    @success="handleSuccess(item.attachments, ...arguments)"
    :on-preview="handlePreview"
    @remove="handleRemove(item.attachments, ...arguments)"
    :before-upload="beforeUpload"
    :file-list="item.attachments"
    multiple>
       <i class="el-icon-upload"></i>
       <div class="el-upload__text">Arraste os arquivos aqui ou <em>clique para selecionar</em></div>
  </upload>
</div>
```

To finally do this with the dynamically attachments:

```js
methods: {
    handleSuccess(attachments, response, file, fileList) {
      return attachments.splice(0, attachments.length, ...fileList
        .map(item => (item.response ? pick(['name', 'url'], item.response) : pick(['name', 'url'], item))));
    },
}
```

I built my own version of [Element-ui](https://npmjs.org/package/element-cotabox) until you guys decided or not to add this solution. Any other solution will be excellent, this was the most easily way that I found, for not change this component that works pretty well in the rest of the application.

**Comment by Leopoldthecoder** [comment]
In this case you can pass a high order function to `on-success`:
```html
<div v-for="item in items">
  <upload
    :action="UPLOAD_URL"
    :on-success="getSuccessHandler(item.attachments)">
    <i class="el-icon-upload"></i>
  </upload>
</div>
```

```js
methods: {
getSuccessHandler(attachments) {
  return (response, file, fileList) => {
    this.handleSuccess(attachments, response, file, fileList)
  }
},
handleSuccess(attachments, response, file, fileList) {
  return attachments.splice(0, attachments.length, ...fileList
    .map(item => (item.response ? pick(['name', 'url'], item.response) : pick(['name', 'url'], item))));
  }
}
```

Here's a demo: https://jsfiddle.net/leopoldthecuber/3ctoomcL/

**Comment by kavalcante** [comment]
Great idea, I haven't thought that way. I think it's got a better approach.

Closing the PR. Thanks for the help :)

**Comment by yoyo837** [comment]
In my case, if I want to trigger form validation (something rules for it), is there a better way?

```html
<el-form>
    <el-form-item>
        <el-upload>
        </el-upload>
    </el-form-item>
</el-form>
```

**Comment by kavalcante** [comment]
@yoyo837 Here's a example of how to validate el-upload inside a v-for:

```html
<el-form ref="order" :model="order">
  <div v-for="(product, index) in order.products)">
    <el-form-item :rules="{ required: true, message: '', trigger: 'change' }" :prop="`products.${index}.attachments`">
      <el-upload
        :action="UPLOAD_URL"
        name="document"
        :on-remove="getRemoveHandler(product.attachments)"
        multiple
        :on-success="getSuccessHandler(product.attachments)"
        :file-list="product.attachments">
        <el-button size="small" type="primary" plain>Attachments</el-button>
      </el-upload>
    </el-form-item>
  <div>
</el-form>
```

**Pull request closed without merging**
