### PR TITLE
Picker only emit user change

### PR DESCRIPTION
**Pull request by Dreamacro**
`DatePicker` 系列的 `change` 事件改为仅响应用户交互

### CODE REVIEW

**Comment by wacky6** [comment]
I prefer a cleaner approach. Using flags to distinguish user interaction seems unnecessarily complicated.

**Comment by Dreamacro** [comment]
@wacky6 
Emmmm, which approach are you prefer?

**Comment by wacky6** [comment]
I prefer emit change in user-related event handlers, leave out the flags.

**Comment by wacky6** [comment]
@Leopoldthecoder 

I am working on a cleaner picker implementation, with bug fixes and refined `default-value` feature. Should be able to get rid of the `user` flag in this PR.

**Comment by Leopoldthecoder** [comment]
@wack6 Cool

**Comment by Leopoldthecoder** [comment]
@wacky6 In terms of `default-value`, after #7073, range typed DatePicker would break if the initial value is `[]`: https://jsfiddle.net/leopoldthecuber/LkbeLLd9/ . #7233 is a fix. Just a heads-up for your refining it.

**Comment by wacky6** [comment]
Got it.

**Comment by wacky6** [comment]
*-Picker rework mostly finished.

Updating / adding tests. Should be able to PR later this week.

Spoiler: 
* experimental support to bind non-Date value, controlled with `valueFormat`
* fix navigation issue
* refined default-value, add support for array, make it reactive
* refined highlight, can highlight today/current/default separately 
* simplified internal implementation, make room for more features.

**Comment by wacky6** [comment]
May later rework date-table to support Daylight Saving Times.

Currently, it does not highlight properly.

image

**Comment by Leopoldthecoder** [comment]
Wow that's great

**Pull request merged**
