### PR TITLE
npm run test error

### PR DESCRIPTION
**Pull request by earlymeme**
Please makes sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's [Contributing Guide](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.md).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Rebase before creating a PR to keep commit history clear.
* [x] Add some descriptions and refer relative issues for you PR.

npm run test error for windows

### CODE REVIEW

**Comment by QingWei-Li** [comment]
团队的开发习惯就是 dev 之前自动运行一次 install

**Comment by baiyaaaaa** [comment]
@QingWei-Li +1

**Comment by earlymeme** [comment]
npm run test error这个呢

**Comment by QingWei-Li** [comment]
@earlymeme 嗯 那个要修，麻烦保留 bootstrap 谢谢 : )

**Comment by QingWei-Li** [comment]
诶 为啥这么多内容。。。重新开一个 pr 吧 😂

**Pull request closed without merging**
