### PR TITLE
Allow to create new items using keyboard only

### PR DESCRIPTION
**Pull request by lukaszb**
IMHO components like that should work without need to use mouse or having to use arrow keys to hover before typing enter. With this change user would be able to simply type a value in and hit enter to add it. It's way more convenient in my view.

### CODE REVIEW

**Comment by xeoshow** [comment]
Exactly the feature what I need, thanks!

**Comment by marceloavf** [comment]
Great feature!

**Comment by lukaszb** [comment]
@Leopoldthecoder any chances you can review this and tell if it's acceptable?

**Comment by lukaszb** [comment]
@Leopoldthecoder any chances you can review this and tell if it's acceptable?

**Comment by Leopoldthecoder** [comment]
For this purpose, you can use `default-first-option`: https://jsfiddle.net/ma106uxt/ .

There is a minor unexpected behavior though: https://jsfiddle.net/ma106uxt/1/ .When you type `'h'`, Select highlights `HTML` instead of the newly created `h`. I have fixed this in #8790 to ensure the created option always gets highlighted before other options.

**Comment by lukaszb** [comment]
@Leopoldthecoder cool, thanks! Totally missed that option. Do you consider adding it to the examples?

**Comment by Leopoldthecoder** [comment]
@lukaszb Sure.

**Pull request closed without merging**
