### PR TITLE
Table: 新增rowSpan 分组合并功能

### PR DESCRIPTION
**Pull request by gloxing**
Please make sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer relative issues for you PR.

新增属性
rowSpans JSON数组, 用于确认合并项 数组格式 要有keyIndex用于标识数据
rowSpanKey String  keyIndex对应的key
如有数组data[{id:'1',name:'liu',date:'2017'},{id:'2',name:'xin',date:'2018']
rowSpanKey = id
rowSpans[{keyIndex:'2',name:2}]
表示 id为1的name列rowSpan为2

注意：因Vue 不能检测属性被添加的限制, 所以渲染后的修改注意使用$set

### CODE REVIEW

**Comment by gloxing** [comment]
因Vue 不能检测属性被添加的限制, 所以注意使用$set

**Comment by lerit** [comment]
expect merge it,thanks

**Comment by MissCuriosity** [comment]
现在表格中兼容rowspan是已经支持了吗？？

**Comment by lerit** [comment]
还没呢吧，@MissCuriosity

**Comment by Leopoldthecoder** [comment]
Supported in 2.0

**Pull request closed without merging**
