### PR TITLE
Input&Select: fix cursor goes to the end of the text(#10611)

### PR DESCRIPTION
**Pull request by xuzaixian**
Please make sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by xuzaixian** [comment]
fix cursor goes to the end of the text #10611

**Comment by samjo-lendit** [comment]
Also, this commit (https://github.com/ElemeFE/element/commit/0b7e9dae5cbc572359fd8a8e45d799a1712fe7580) also changed el-select. I think that same patch should be applied to el-select.

**Comment by xuzaixian** [comment]
@samjo-lendit But,I can't trigger the same bug when i type Korean in el-select.
Can you reproduce ?

**Comment by samjo-lendit** [comment]
@xuzaixian here is a reproduction code! https://jsfiddle.net/samjo/ygbquxzp/3/

**Comment by xuzaixian** [comment]
@samjo-lendit  
Now, el-select also apply this patch  😆

**Pull request merged**
