### PR TITLE
Checkbox: change event only triggers on user input

### PR DESCRIPTION
**Pull request by Leopoldthecoder**
Please make sure these boxes are checked before submitting your PR, thank you!

* [ ] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md)).
* [ ] Make sure you are merging your commits to `dev` branch.
* [ ] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by wacky6** [comment]
DEMO 有地方要修正： checkbox.md > intermediate

```
handleCheckAllChange(event) {
    this.checkedCities = event.target.checked ? cityOptions : [];
    this.isIndeterminate = false;
},
```
 -> 
```
handleCheckAllChange(value) {
    this.checkedCities = value ? cityOptions : [];
    this.isIndeterminate = false;
},
```

---

限定最多可选项目时好像有问题：https://jsfiddle.net/edx8abfr/2/
点击 广州 或者 深圳 会触发 change

**Comment by Leopoldthecoder** [comment]
@wacky6 OK，我看一下。

**Comment by Leopoldthecoder** [comment]
@wacky6 Done.

**Comment by wacky6** [comment]
It works correctly now. 👍

**Pull request merged**
