### PR TITLE
Included pt-br locale

### PR DESCRIPTION
**Pull request by vedovelli**

### CODE REVIEW

**Comment by Leopoldthecoder** [comment]
Thanks for contributing!

Could you tell me what the difference is bewteen pt-br and [pt](https://github.com/ElemeFE/element/blob/dev/src/locale/lang/pt.js)?

**Comment by vedovelli** [comment]
@Leopoldthecoder Hello! There are slight differences from pt (which is from Portugal) and pt-br (which is from Brazil). Thanks!

**Comment by emtudo** [comment]
thanks @vedovelli abs!

**Comment by kaibady** [comment]
Why is this lowercase

**Pull request merged**
