### PR TITLE
Pagination: disabled prev and next buttons should not trigger click

### LINKED ISSUE #10627: The next and prev buttons of the disabled of the [Bug Report] pagination control trigger a current-change event
### Element UI version
2.3.3

### OS/Browsers version
window10

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/oscar_xi/nh7ho83e/4/](https://jsfiddle.net/oscar_xi/nh7ho83e/4/)

### Steps to reproduce
点击prev或者next按钮。

### What is Expected?
不会触发current-change事件

### What is actually happening?
会触发一次current-change事件

### PR DESCRIPTION
**Pull request by Leopoldthecoder**
Please make sure these boxes are checked before submitting your PR, thank you!

Fixes #10627

* [ ] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md)).
* [ ] Make sure you are merging your commits to `dev` branch.
* [ ] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by CHEN-DONG** [comment]
why close item， my issue is follow your guide

**Comment by Leopoldthecoder** [comment]
因……因为已经修好了啊……

**Comment by CHEN-DONG** [comment]
ok, i am sorry.
i will update package and try again.
thanks a lot.

**Comment by CHEN-DONG** [comment]
请问一下 我要怎么更新组件呢 等下一个版本？

**Comment by Leopoldthecoder** [comment]
是的，等我们发布下一个版本，然后你 `npm upgrade element-ui` 就行。

**Comment by CHEN-DONG** [comment]
发布新版本会在哪里通知么

**Comment by CHEN-DONG** [comment]
@Leopoldthecoder 发布新版会在哪里通知么

**Comment by Leopoldthecoder** [comment]
官网更新日志或者 GitHub Releases

**Comment by 17600611218** [comment]
这个版本之后如果设置了total，在设置current-page，total生效了，数据也显示是某页的内容，但是页码没有改变 @Leopoldthecoder

**Pull request merged**
