### PR TITLE
 input: computed the 'showClear' the emit

### PR DESCRIPTION
**Pull request by liaoliaojun**
input:  抛出clear的显示状态
Please make sure these boxes are checked before submitting your PR, thank you!

* [ ] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md)).
* [ ] Make sure you are merging your commits to `dev` branch.
* [ ] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by LIAOTOW** [comment]
image
用于眼睛icon同步显示隐藏状态

**Comment by wacky6** [comment]
写个jsfiddle吧。没太懂你想实现什么

**Comment by LIAOTOW** [comment]
@wacky6  https://jsfiddle.net/ku0Lsnr2/24/
希望可以实时获取clear的显示状态

**Comment by ziyoung** [comment]
这个属性好鸡肋。

**Comment by LIAOTOW** [comment]
@ziyoung  https://jsfiddle.net/ku0Lsnr2/82/
需要监听好多事件才可以实现

**Pull request closed without merging**
