### PR TITLE
[tag.scss] fix a sass warning, due to omission of unit '%', in sass method mix()

### PR DESCRIPTION
**Pull request by yangxu52**
fix a sass warning, due to omission of unit '%', in sass method color.mix(), in custom method genTheme, in packages\theme-chalk\src\tag.scss

warning:Deprecation $weight: Passing a number without unit % (0) is deprecated.
Reference: https://sass-lang.com/documentation/breaking-changes/function-units#weight

Process: add '%' after number '0' in custom method 'genTheme()' 's call, which use sass method 'color.mix()'

Please make sure these boxes are checked before submitting your PR, thank you!

* [✓] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [✓] Make sure you are merging your commits to `dev` branch.
* [✓] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by Autumnwater** [comment]
it is merge?

**Comment by Autumnwater** [comment]
合并了么，我这里用的

**Comment by Autumnwater** [comment]
"element-ui": "^2.15.13","sass": "1.58.3",，还是报错

**Comment by yangxu52** [comment]
> 合并了么，我这里用的

PR早提了 没有给合并

自己手动改一下吧，可以编译不报警告

**Comment by Autumnwater** [comment]
嗯，按你的改了，就是每次 install又要重来一次

**Comment by yangxu52** [comment]
> 嗯，按你的改了，就是每次 install又要重来一次

package.json -> scripts
` "prepare": "cd node_modules && sass-migrator division **/*.scss && cd .. && node .prepare/fix-sass-warning.js"`

package.json - > devDependencies
`"sass-migrator": "^1.7.3",`

.parepare/fix-sass-warning.js (module js，你可以改写成commonjs)
``` javascript
import { readFile, writeFile } from 'node:fs'

const filePath = 'node_modules\\element-ui\\packages\\theme-chalk\\src\\tag.scss'
const targetStr = '0, '
const replaceStr = '0%, '
readFile(filePath, (err, data) => {
  if (err) {
    return console.error(err)
  }
  let str = data.toString()
  str = str.replaceAll(targetStr, replaceStr)
  writeFile(filePath, str, (err) => {
    if (err) {
      return console.error(err)
    }
  })
})
```

**Pull request closed without merging**
