### PR TITLE
update popover/tooltip docs

### PR DESCRIPTION
**Pull request by Leopoldthecoder**
Please makes sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's [Contributing Guide](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.md).
* [x] Rebase before creating a PR to keep commit history clear.
* [x] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by QingWei-Li** [comment]
lgtm

**Comment by Leopoldthecoder** [comment]
@baiyaaaaa @QingWei-Li @csvwolf 
我看了一下，tower 上的分歧应该都已经解决了，各位再查一下？如果都解决了，网站似乎可以发了？

**Comment by QingWei-Li** [comment]
发发发

**Comment by csvwolf** [comment]
应该可以了？

**Comment by Leopoldthecoder** [comment]
OK，我再让 UED 过一遍。

**Pull request merged**
