### PR TITLE
[Dialog] When dialog's <appendToBody> is true, remove DOM node after destroyed.

### PR DESCRIPTION
**Pull request by Allenice**
Please make sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by Leopoldthecoder** [comment]
Hi, why do you need this feature? Is there any demo?

**Comment by Allenice** [comment]
Dialog's DOM nodes are still in body when I go to another page. When I go back and open dialog again, it will create a new one, but old one is still here.
demo: https://jsfiddle.net/Allenice/b7k0jsd0/4/

**Comment by languanghao** [comment]
@Allenice @Leopoldthecoder  It seems like you don't check `this.$el.parentNode != null`，I use the dialog in a 'div' and use 'v-if' control the dialog show/hide. Now I got the error:   

[Vue warn]: Error in destroyed hook: "TypeError: Cannot read property 'removeChild' of null"

**Comment by lukaszptr** [comment]
@languanghao is right, got the same problem

**Comment by Leopoldthecoder** [comment]
@languanghao @lukaszptr This will be fixed in the next release

**Pull request merged**
