### PR TITLE
Carousel: fix async item not refreshing view issue

### PR DESCRIPTION
**Pull request by Leopoldthecoder**
Please makes sure these boxes are checked before submitting your PR, thank you!

* [ ] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md)).
* [ ] Make sure you are merging your commits to `dev` branch.
* [ ] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by JanlyH** [comment]
升级到1.2.3还有有这个问题啊，ajax请求后台数据渲染到页面，第一页不会展示

**Comment by Leopoldthecoder** [comment]
@JanlyH 因为这个 PR 还没合

**Comment by JanlyH** [comment]
@Leopoldthecoder OK，辛苦了！

**Comment by LYlanfeng** [comment]
请问下1.2.3版本是不是这个问题没有解决

**Comment by Leopoldthecoder** [comment]
@LYlanfeng 对，这个改动还没发布

**Comment by fallenner** [comment]
1.3.7问题依旧存在@Leopoldthecoder

**Comment by Leopoldthecoder** [comment]
@fallenner 有问题请准备 demo

**Pull request merged**
