### PR TITLE
Input-Number: Fix precision problem (#15292)

### LINKED ISSUE #15292: [Bug Report] El-input-number precision(rounding) isn't most correctly working.
### Element UI version
2.8.2

### OS/Browsers version
Chrome

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/Danik_codepenIO/pen/NmEOWL?&editable=true

### Steps to reproduce
Enter 2,455 into el-input-number with precision:2. El - input-number has rounded to 2,46.
Enter 2,465 into el-input-number with precision:2. El - input-number has rounded to 2,46.

### What is Expected?
Expected that 2,465 would be rounded to 2.47.

### What is actually happening?
Method 'toPrecision'  isn't correct working.
Should to do (Math.round((value*pow)).toFixed(precision))/pow

### PR DESCRIPTION
**Pull request by susiwen8**
Please make sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer relative issues for you PR.

Replace toFixed() by Math.round(), because toFixed() follow Banker's Round 
https://blog.csdn.net/fjnpysh/article/details/79077997

Close #15292

### CODE REVIEW

**Comment by wacky6** [comment]
What's wrong with `.toFixed` ? Please elaborate on your changes.

**Comment by wacky6** [comment]
Does it really matter? 

IEEE 754 float points won't correctly reflect human's definition of precision / number of decimal places anyway.

For reference: 
* https://github.com/d3/d3-format/issues/27
* https://www.ecma-international.org/ecma-262/6.0/#sec-number.prototype.tofixed

---

And, JavaScript spec says nothing about Banker's Round. Please refer to ECMAScript spec instead of CSDN articles.

**Comment by susiwen8** [comment]
@wacky6 Well, someone point out this issue, so for some people it matter.

I did some test in Chrome dev tool, under toFixed() case, if the number before 5 is odd it will add 1, even number won't add 1. 
4.115 -> 4.12
4.125 -> 4.12
4.135 -> 4.14
4.145 -> 4.14

From ECMAScript or MDN documents, there is no prove to support 'banker's round', but I look through some example those had same problem with toFixed() precision, they all suggest to use Math.round() to avoid this problem
Screen Shot 2019-04-30 at 09 56 58

**Comment by susiwen8** [comment]
Hi @wacky6  have you considered this?

**Pull request merged**
