### PR TITLE
Select: Added pass popover options from select

### PR DESCRIPTION
**Pull request by bogkov**
Please make sure these boxes are checked before submitting your PR, thank you!

* [x ] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md)).
* [x ] Make sure you are merging your commits to `dev` branch.
* [x ] Add some descriptions and refer relative issues for you PR.

Can't pass popper options:
`{
  preventOverflowOrder: ['left', 'right'],
  forceAbsolute: true
}`

Example where it's necessary:
https://imgur.com/a/dxGE5vX
https://jsfiddle.net/IamSCORPION/mmx38qxw/3923/

### CODE REVIEW

**Comment by ziyoung** [comment]
@bogkov We add `popper.js` as `dependencies` in next version and the option for `popper.js` has changed.  https://popper.js.org/popper-documentation.html#Popper.Defaults

**Comment by bogkov** [comment]
@ziyoung I saw #11778, that will be in version 3, but this will not fix this problem.

**Comment by ziyoung** [comment]
@bogkov I mean the popper option of v3 is different from v2. The popper option may be like below
```js
{ 
  modifiers: {
     computeStyle: {
        gpuAcceleration: false
     }
  }
}
```

**Comment by bogkov** [comment]
@ziyoung I understand it. This is a patch for v2.

**Pull request closed without merging**
