### PR TITLE
Tree：[without-children]  In the check box state, the child node state of the current node is not associated with it

### PR DESCRIPTION
**Pull request by Holybasil**
Please make sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [ ] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by luckyCao** [comment]
如果是修复一个 bug，请提供一个可复现的链接

**Comment by Holybasil** [comment]
> 如果是修复一个 bug，请提供一个可复现的链接

不是修复bug 是增加一个props

**Comment by luckyCao** [comment]
@Holybasil 你新增的 api 和 check-strictly 有什么区别？

**Comment by Holybasil** [comment]
check-strictly
check-strictly
without-children
without-children
check-strictly 表示当前节点和其父节点子节点都无关
without-children 表示当前节点仍与其父节点有关 而摒弃子节点（某些情况需要）

**Pull request closed without merging**
