### PR TITLE
Pagination: fix user can not set currentPage in some condition.

### PR DESCRIPTION
**Pull request by furybean**
Please makes sure these boxes are checked before submitting your PR, thank you!

* [ ] Make sure you follow Element's [Contributing Guide](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.md).
* [ ] Make sure you are merging your commits to `dev` branch.
* [ ] Rebase before creating a PR to keep commit history clear.
* [ ] Add some descriptions and refer relative issues for you PR.

#1316

### CODE REVIEW

**Comment by furybean** [comment]
晚上补测试。

**Comment by Kingwl** [comment]
话说这改哪里了，，，，

**Comment by furybean** [comment]
保证设置属性 watch 的优先级比较高，否则设置属性就永远也进不了 watch 了，vue 的 watch 会抛弃一部分中间结果导致的。

**Comment by Kingwl** [comment]
233 thanks

**Pull request merged**
