### PR TITLE
DatePicker: fix#22039 修复2.15.9 版本时间组件控制台报错

### PR DESCRIPTION
**Pull request by chenchenwuai**
Please make sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer relative issues for you PR.
相关issue链接: 
+ https://github.com/ElemeFE/element/issues/22039
+ https://github.com/ElemeFE/element/issues/22025
+ https://github.com/ElemeFE/element/issues/21978
+ https://github.com/ElemeFE/element/issues/21941

### CODE REVIEW

**Comment by MARIOMARUI** [comment]
居然没人管。

**Comment by MARIOMARUI** [comment]
为何我没有找到currentPlacement 的定义之处。

**Comment by chenchenwuai** [comment]
> 为何我没有找到currentPlacement 的定义之处。

在 `src/utils/vue-popper` 里面

**Comment by imba97** [comment]
> 居然没人管。

应该是有人已经修掉了 #21908

**Pull request closed without merging**
