### PR TITLE
bug(#18456) in popconfirm onConfirm/onCancel fixed 

### PR DESCRIPTION
**Pull request by itsmeJithin**
Please make sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by Alexeykhr** [comment]
These 2 PR would be join into one :)
https://github.com/ElemeFE/element/pull/18324

**Comment by Alexeykhr** [comment]
#18456

**Comment by praveenpuglia** [comment]
Thanks. Just came here to see if a PR for this already exists otherwise I would have submitted one. It has caused me a bunch of hours.

**Comment by iamkun** [comment]
Now fixed to the correct 'confirm' and 'cancel' event name in #20240

**Pull request closed without merging**
