### PR TITLE
Tooltip: refactor code no longer generates additinal html tag

### PR DESCRIPTION
**Pull request by QingWei-Li**
Please makes sure these boxes are checked before submitting your PR, thank you!

* [ ] Make sure you follow Element's [Contributing Guide](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.md).
* [ ] Make sure you are merging your commits to `dev` branch.
* [ ] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by reverland** [comment]
所以，发现一系列checkbox中，包裹el-tooltip那一项会完全不一样。。

**Comment by QingWei-Li** [comment]
@reverland 怎么了大佬 没懂你意思

**Comment by reverland** [comment]
卧槽，大佬在线

**Comment by reverland** [comment]
screen shot 2017-03-13 at 8 46 23 pm

**Comment by reverland** [comment]
screen shot 2017-03-13 at 8 46 57 pm

**Comment by reverland** [comment]
卧槽是不是我升级没成功。。。

**Comment by reverland** [comment]
@QingWei-Li 没事。。。我傻逼了。。不知道为啥本地是1.1.3.。。

**Comment by nei2000** [comment]
我用了1.2.X以上版本tooltip居然没有起效不知道是怎么回事

**Pull request merged**
