### PR TITLE
fix overflow

### PR DESCRIPTION
**Pull request by yozman**
Please make sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by Leopoldthecoder** [comment]
Hi, could your write a demo where this update is necessary?

**Comment by yozman** [comment]
@Leopoldthecoder 
http://element.eleme.io/#/zh-CN/component/upload
官方文档上就有的 bug
子元素 `transform` 的时候
父元素有 `border-radius`
且想 `overflow:hidden`
需要指定下 `z-index`

**Comment by yozman** [comment]
@Leopoldthecoder 
话说自动构建为啥失败了？
https://travis-ci.org/ElemeFE/element/builds/329054919?utm_source=github_status&utm_medium=notification
日志上说 `The command "eval yarn " failed.`

**Comment by Leopoldthecoder** [comment]
> 子元素 transform 的时候
> 父元素有 border-radius
> 且想 overflow:hidden

@yozman 写个例子吧

**Comment by yozman** [comment]
@Leopoldthecoder 
https://weibo.com/2984294751/FEwtVnlEm

**Comment by Leopoldthecoder** [comment]
get

**Pull request merged**
