### PR TITLE
Autocomplete: add custom width setting for suggestion

### PR DESCRIPTION
**Pull request by wahaha2012**
Please make sure these boxes are checked before submitting your PR, thank you!

* [ ] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md)).
* [ ] Make sure you are merging your commits to `dev` branch.
* [ ] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by ziyoung** [comment]
@wahaha2012 这个 pr 的目的是？

**Comment by wahaha2012** [comment]
@ziyoung 目前suggestion的宽度值使用的是Input的宽度，有些业务场景下，input的尺寸不一定很宽，为了更好的展示suggestion内容，需要自定义suggestion列表的宽度。

**Comment by Leopoldthecoder** [comment]
用 CSS 覆盖一下吧：https://jsfiddle.net/83gu27ar/1/ 。专门加个属性有些冗余了。

**Comment by mygu** [comment]
@Leopoldthecoder 用css覆盖会导致所有的suggestion列表宽度都一样了，请问这样的问题如何解决？

**Pull request closed without merging**
