### PR TITLE
Drawer: fix focus bug

### PR DESCRIPTION
**Pull request by cs1707**
Please make sure these boxes are checked before submitting your PR, thank you!

ref: #19902

* [x] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by JeremyWuuuuu** [comment]
Hey, I am the contributor who contributed this component, the original idea of adding `tabindex` to `title` is because we want the screenreader to read the title content for the users who uses screenreader device, but I did have made a mistake on adding `tabindex` towards the container.

**Comment by JeremyWuuuuu** [comment]
The change itself was legit though, but still, I think you do not need to remove the `nextTick` operation because that's how it works, also I didn't add `trap-focus` for this component, which needs trap the focus(keyboard navigation) inside this content.

**Comment by cs1707** [comment]
Hi, Thanks for your reply. In my opinion that `tabindex` can improve keyboard accessibility. For screen reading we should use `aria-label` or `role` attributes to improve accessibility. So I removed the `tabindex` from the title.

**Comment by cs1707** [comment]
For dialog or drawer components I think trap-focus is necessary. We have the same opinion about this. And like the bootstrap antd material ui they all have implementations for it.

**Comment by JeremyWuuuuu** [comment]
> For dialog or drawer components I think trap-focus is necessary. We have the same opinion about this. And like the bootstrap antd material ui they all have implementations for it.

The change is legit, adding `trap-focus` functionality would be a great upgrade.

**Comment by cs1707** [comment]
> > For dialog or drawer components I think trap-focus is necessary. We have the same opinion about this. And like the bootstrap antd material ui they all have implementations for it.
> 
> The change is legit, adding `trap-focus` functionality would be a great upgrade.

This feature may be updated next time 😄

**Pull request merged**
