### PR TITLE
[Carousel] Add an optional label to indicator buttons

### PR DESCRIPTION
**Pull request by paul-blundell**
Please makes sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's contributing guide
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer relative issues for you PR.

Adds an optional label to the indicator buttons on the carousel. Can be used only if required like so:

```
<n-carousel-item label="Slide 1">
  <h3>My Slide</h3>
</n-carousel-item>
```

### CODE REVIEW

**Comment by paul-blundell** [comment]
That was a fair point, I didn't think about the default theme.

I have added a new prop (defaults to false) for indicator-labels on the carousel itself. If true then it applies another class to the button and adds the label text from carousel-item.

Please let me know your thoughts.

**Comment by Leopoldthecoder** [comment]
image

I tried the new commits and got the above. It doesn't seem to be desired. 

To get what you proposed in #4153, I think more CSS needs to be added. For example, if `indicator-labels` is true, another class should be applied to `<ul>` to deal with its positioning and width. Besides, since the indicators can be both inside and outside the slides (governed by `indicator-position`), it makes sense that labelled indicators should look nice in both scenarios.

What do you think? Could you update this PR?

**Comment by paul-blundell** [comment]
Updated to fix that issue. Added a class to the `<ul>` instead like you suggested.
There is still some overlap on smaller screens when you have a lot of carousel items, but maybe this should be down to the user to style as required or limit the number of items?

**Comment by Leopoldthecoder** [comment]
I updated this. Removed `indicatorLabels` because we can check if items have `label`s inside main.vue.

**Pull request merged**
