### PR TITLE
support button autofocus && autofocus message box confirm button

### PR DESCRIPTION
**Pull request by baiyaaaaa**
Please makes sure these boxes are checked before submitting your PR, thank you!

* [ ] Make sure you follow Element's [Contributing Guide](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.md).
* [ ] Rebase before creating a PR to keep commit history clear.
* [ ] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by baiyaaaaa** [comment]
#721

**Comment by xingchch** [comment]
At present, The defoult focus is on ok button.  I need to to make default focus on cancel button , 
Is there any way to do it?

**Comment by gooqiao** [comment]
@xingchch 请问您解决了吗？ 默认focus取消按钮，或者默认不focus确认按钮也可以。

**Comment by afuning** [comment]
how to delete message box confirm button autofocus?

**Comment by gooqiao** [comment]
@sunorign  我绑定了弹框出现时的事件，然后用dom移除了

**Comment by meiliTang** [comment]
> @sunorign 我绑定了弹框出现时的事件，然后用dom移除了

弹窗出现时的事件？是哪个钩子函数？方便告知吗

**Comment by meiliTang** [comment]
> 如何删除消息框确认按钮自动对焦？

你好，你的问题解决了吗？

**Pull request merged**
