### PR TITLE
Button: fix disabled priority

### PR DESCRIPTION
**Pull request by cs1707**
Please make sure these boxes are checked before submitting your PR, thank you!

close: #21069

* [x] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by cameron-martin** [comment]
This PR introduces a bug. If the button initially is not disabled, but changes to disabled, it does not correctly re-render.

This is because `this.$options.propsData.hasOwnProperty('disabled')` introduces a dependency on the `disabled` prop but in a way that isn't tracked by vue's reactivity system.

**Comment by cameron-martin** [comment]
I've created a codesandbox to demonstrate the issue: https://codesandbox.io/s/cocky-kowalevski-468lw?file=/src/App.vue

If you change element-ui to 2.15.6 the button does disable correctly.

**Comment by jeremybatesDC** [comment]
> https://codesandbox.io/s/cocky-kowalevski-468lw?file=/src/App.vue

This is broken again as of 2.15.7

**Comment by robertovaldesperez** [comment]
@cs1707 @cameron-martin @jeremybatesDC @iamkun @matjaz Any news about this? I am using element plus version 2.9.7 (latest) and i want to disable the form but not a specific button.

**Pull request merged**
