### PR TITLE
el-select : Add tab key support

### PR DESCRIPTION
**Pull request by xi-osman**
This change will allow the user select the highlighted item when tabbing off. 

Please make sure these boxes are checked before submitting your PR, thank you!

* [X] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md)).
* [X] Make sure you are merging your commits to `dev` branch.
* [X] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by ziyoung** [comment]
Which issue does this pr fix?

**Comment by xi-osman** [comment]
This allows you to hit the key tab to choose an item in el-select. So tab or enter allows you to select.

**Comment by wacky6** [comment]
Why is this necessary. Native select won't let you tab to other components unless you press enter to select an option. https://jsfiddle.net/uc5yx9a7/

**Comment by ziyoung** [comment]
You can use the keyboard's up and down arrow keys to select an option. 
ElSelect is similar to the native select. So pressing tab key will jump to next element which can be focused.

**Comment by ziyoung** [comment]
You can use the keyboard's up and down arrow keys to select an option. 
ElSelect is similar to the native select. So pressing tab key will jump to next element which can be focused.

**Comment by ziyoung** [comment]
You can use the keyboard's up and down arrow keys to select an option. 
ElSelect is similar to the native select. So pressing tab key will jump to next element which can be focused.

**Comment by ziyoung** [comment]
You can use the keyboard's up and down arrow keys to select an option. 
ElSelect is similar to the native select. So pressing tab key will jump to next element which can be focused.

**Comment by ziyoung** [comment]
You can use the keyboard's up and down arrow keys to select an option. 
ElSelect is similar to the native select. So pressing tab key will jump to next element which can be focused.

**Comment by ziyoung** [comment]
You can use the keyboard's up and down arrow keys to select an option. 
ElSelect is similar to the native select. So pressing tab key will jump to next element which can be focused.

**Comment by ziyoung** [comment]
You can use the keyboard's up and down arrow keys to select an option.
ElSelect is similar to native select. Pressing tab key will jump to next element which can be focused.

**Comment by ziyoung** [comment]
You can use the keyboard's up and down arrow keys to select an option.
ElSelect is similar to native select. Pressing tab key will jump to next element which can be focused.

**Comment by ziyoung** [comment]
You can use the keyboard's up and down arrow keys to select an option.
ElSelect is similar to native select. Pressing tab key will jump to next element which can be focused.

**Pull request closed without merging**
