### PR TITLE
Notification: add onClick handler

### PR DESCRIPTION
**Pull request by amouillard**
Added an event handler on click of notification's div

Please makes sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by Leopoldthecoder** [comment]
I'm afraid a click handler on Notification is not quite necessary. Could you tell me why you need this?

**Comment by amouillard** [comment]
I wanted to be able to change to a page relevant to the notification's content.

For example if somebody sent you a private message and you're using the notification component, you could then simply click the notification window and get redirected to this private message !

**Comment by Leopoldthecoder** [comment]
OK, could you add this handler to the [docs](https://github.com/ElemeFE/element/blob/dev/examples/docs/en-US/notification.md#options)?

**Comment by amouillard** [comment]
Sure, I'll add some documentation.

**Comment by amouillard** [comment]
I failed to update the current pull request so added the documentation in [this one](https://github.com/ElemeFE/element/pull/4235), sorry.

**Pull request merged**
