### PR TITLE
MessageBox: fix bug for default inputValue

### PR DESCRIPTION
**Pull request by mu-yu**
Please makes sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/dev/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] fix issue #2737

### CODE REVIEW

**Comment by lideyang** [comment]
为什么我按修改后的代码来设置的inputValue依然会报错说：Cannot read property 'dispatch' of undefined

**Comment by Leopoldthecoder** [comment]
@lideyang 我还没看这个 PR，看过之后再给反馈。

**Comment by Leopoldthecoder** [comment]
@lideyang 我试了一下没问题，你是怎么设置的？请贴一下代码。

**Comment by Leopoldthecoder** [comment]
#2909

**Pull request closed without merging**
