### PR TITLE
Adjustment spanish version

### PR DESCRIPTION
**Pull request by Gonzalo2310**
Please make sure these boxes are checked before submitting your PR, thank you!

* [ ] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md)).
* [ ] Make sure you are merging your commits to `dev` branch.
* [ ] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by Leopoldthecoder** [comment]
It seems you have merged our `dev` branch into your local `es-doc` branch. Please don't do that, or we'll face a lot of conflicts when merging `es-doc` into `dev`.

**Comment by Gonzalo2310** [comment]
What a mess I'm making. Forgive me all this. I'm a mess with branches, obviously.

**Comment by Gonzalo2310** [comment]
How do I fix this?

**Comment by Leopoldthecoder** [comment]
No problem. You can try:
- Checkout a new branch from remote `es-doc` (by remote I mean this repo, not your own fork)
- When you're in that new branch, do the following:
```
git cherry-pick 4c43a79
```
```
git cherry-pick 9501744
```
```
git cherry-pick be3756b
```
- Push this new branch to your forked repo, and send another PR with it

**Comment by Gonzalo2310** [comment]
I've done the fork again.
I hope it has now been resolved in the new pull request. #8480

**Comment by Leopoldthecoder** [comment]
Great! #8480 looks good, so I'll close this one.

**Pull request closed without merging**
