### PR TITLE
Change hard-coded padding of dialog body to be responsive to sass var

### PR DESCRIPTION
**Pull request by haoranyu**
Please make sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by island205** [comment]
what is your purpose?

**Comment by haoranyu** [comment]
When I do some customization by changing `$--dialog-padding-primary` both the padding on header and footer is changed. However, the left and right paddings of the dialog body remain `20px` which break the alignment of the visual design of the dialog.

**Comment by haoranyu** [comment]
In case you cannot get my point, the following is a screenshot after `$--dialog-padding-primary` is set to `40px`. The red bars demonstrate the issue of bad alignment on the dialog body.

**Comment by haoranyu** [comment]
@iamkun Have a look?

**Pull request merged**
