### PR TITLE
More translations

### PR DESCRIPTION
**Pull request by sigfriedCub1990**
Please make sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by Leopoldthecoder** [comment]
Please rebase `es-doc` branch first. Some of the commits are already submitted.

**Comment by sigfriedCub1990** [comment]
Hello @Leopoldthecoder, where should I rebase my branch? I'm a newbie making contributions to GitHub :D, I hope you'll understand. Thanks

**Comment by Leopoldthecoder** [comment]
Try the following steps (in this order):
```bash
git reset f53441c
```

```bash
git stash
```

```bash
git pull [your remote repo name] es-doc --rebase
```

```bash
git stash pop
```

Now you may see some conflicts. Resolve them if any.


```bash
git push [your forked repo name, usually origin] es-doc -f
```

**Comment by sigfriedCub1990** [comment]
Thank you @Leopoldthecoder, I think it solved right now.

**Comment by Leopoldthecoder** [comment]
Not really😂

But that's OK, I can always squash these commits.

**Comment by Leopoldthecoder** [comment]
#8074

**Comment by sigfriedCub1990** [comment]
:laughing: sorry about that, I'll keep reading how to do it the right way ;)

**Pull request merged**
