### PR TITLE
DatePicker: fix date and time value format error 

### PR DESCRIPTION
**Pull request by qingdengyue**
Please make sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer relative issues for you PR.

1.DatePicker: fix date and time value format error

### CODE REVIEW

**Comment by qingdengyue** [comment]
#15791

**Comment by huanghuixin1** [comment]
@qingdengyue 大佬 merge似乎失败了？

**Comment by WaSheep** [comment]
It does not recurrent in your demo

**Comment by qingdengyue** [comment]
> It does not recurrent in your demo

image

**Comment by qingdengyue** [comment]
cc @WaSheep 


> It does not recurrent in your demo

image

**Comment by wacky6** [comment]
依旧有问题
`yyyy年MM月dd日HH时mm分` => `["yyyy年MM月dd", "HH时mm分"]`; “日”字没有了

**Comment by wacky6** [comment]
倾向于 https://github.com/ElemeFE/element/pull/13764 这个方案 
@iamkun @island205

**Pull request closed without merging**
