### PR TITLE
table: fix when data changed, the current highlight row not keep it's state

### PR DESCRIPTION
**Pull request by languanghao**
Please makes sure these boxes are checked before submitting your PR, thank you!

* [ ] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md)).
* [ ] Make sure you are merging your commits to `dev` branch.
* [ ] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by liril-net** [comment]
Hi,

1. 请提供详细的问题描述；
2. #3023 并没有成功修复。

**Comment by languanghao** [comment]
要怎么在JSFiddle里引用我这个JS呢，我本地测试了一下 #3023 是可以的

**Comment by liril-net** [comment]
@languanghao 你也可以自己建个项目，然后我去 clone 下来，查看一下。

**Comment by Leopoldthecoder** [comment]
先关掉了。

**Pull request closed without merging**
