### PR TITLE
Changelog: update for 2.2.0

### PR DESCRIPTION
**Pull request by Gonzalo2310**
Please make sure these boxes are checked before submitting your PR, thank you!

* [ ] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md)).
* [ ] Make sure you are merging your commits to `dev` branch.
* [ ] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by Gonzalo2310** [comment]
First of all. Congratulations.  More than 23,000 stars. They keep growing.

Second. There is a Spanish-language attribute on the menu that does not appear in English or Chinese. It's disabled. 
Attached image.

Check it out, but I think I've done all the pending translations.

captura de pantalla 2018-02-12 a las 14 25 28
captura de pantalla 2018-02-12 a las 14 25 11

**Comment by Leopoldthecoder** [comment]
Ah, this is a mistake, I'll correct it. Thanks for pointing it out.

**Comment by Leopoldthecoder** [comment]
Hi, could you translate another sentence to Spanish?
> Note: we use yarn to lock dependency versions, so you should install dependencies using `yarn` instead of `npm install`.

This is for people who want to contribute to Element. Thanks!

**Comment by Gonzalo2310** [comment]
`Nota: Usamos yarn para bloquear versiones de dependencias, por lo que debería instalar dependencias usando yarn en lugar de npm install.`

That would be in Spanish.

**Comment by Gonzalo2310** [comment]
@Leopoldthecoder 
Whenever I can help, for this repository, another code, or for any other purpose just tell me.
It's a pleasure to be able to help. Always.

**Comment by Leopoldthecoder** [comment]
Appreciate it! Thanks!

**Pull request merged**
