### PR TITLE
DatePicker: bump version

### PR DESCRIPTION
**Pull request by mamalat**
Date picker was updated, but npm need version bump to update package.

### CODE REVIEW

**Comment by mamalat** [comment]
Is there any issue with why this can't be merged?

**Comment by mamalat** [comment]
@QingWei-Li could you please run `npm publish

**Comment by Leopoldthecoder** [comment]
@mamalat The current DatePicker actually has a bug. I'll publish it with the next Element release.

**Comment by mamalat** [comment]
@Leopoldthecoder thanks! Which issue `#` we are talking about, so I can help resolve it.. or you already started on that?

**Comment by Leopoldthecoder** [comment]
No worries, it's resolved already. We'll release this week.

**Pull request merged**
