### PR TITLE
fix carousel bug #5462 && #2189

### PR DESCRIPTION
**Pull request by JoJoChilly**
modified: packages/carousel/src/item.vue
carousel scroll without the end page flash in.

### CODE REVIEW

**Comment by JoJoChilly** [comment]
add: the original has already been fixed in mac, but it still happend on windows browsers like chrome.

**Comment by Leopoldthecoder** [comment]
Unfortunately,  according to my tests, this doesn't work on macOS either. Are you interested in taking a closer look?

**Comment by JoJoChilly** [comment]
Strange because it works in my mac... I will test it on more devices tomorrow.

**Comment by JoJoChilly** [comment]
@Leopoldthecoder Already checked on mac and pro,  works fine. Could you give further information about device type & version and problems?

**Comment by Leopoldthecoder** [comment]
untitled

image

image

As the gif shows, there is a blue flash when the third item is sliding in. Blue is the background color of the last carousel item.

**Comment by JoJoChilly** [comment]
@Leopoldthecoder Got it... I guess it may need a reconfiguration. Will inform you as soon as I finished.

**Comment by JoJoChilly** [comment]
@Leopoldthecoder  Find this better, why not make it inside? https://github.com/ElemeFE/vue-swipe

**Comment by Leopoldthecoder** [comment]
`vue-swipe` is made for mobile devices, so its interactions are different from Carousel.

**Comment by zbagz** [comment]
Same problem here. My content inside the carousel has a background with opacity, so it looks weird when the items are being repositioned.

Maybe we can fix this by adding "transition: 0s" on every element of the carousel and only allow transition time on the active one, his next and his previous item, which are the only ones that should actually be animated and visible on the foreground.

**Comment by Leopoldthecoder** [comment]
Fixed in #6394

**Pull request closed without merging**
