### PR TITLE
responsive layout

### PR DESCRIPTION
**Pull request by baiyaaaaa**
Please makes sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's [Contributing Guide](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.md).
* [x] Rebase before creating a PR to keep commit history clear.
* [x] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by furybean** [comment]
@Leopoldthecoder 看起来可以把网站也做成响应式的了。

**Comment by QingWei-Li** [comment]
网站越来越重了 😂 启动居然要 50s+

**Comment by Leopoldthecoder** [comment]
嗯，我写到这个迭代里。

**Comment by Leopoldthecoder** [comment]
冲突啦

**Comment by QingWei-Li** [comment]
是吧 changelog 很容易冲突，很烦人啊

**Comment by fengsi** [comment]
神马现在还不是responsive的吗？都快要决定用这套了居然来这一出……

**Pull request merged**
