### PR TITLE
[Popconfirm] Init popconfirm component

### PR DESCRIPTION
**Pull request by iamkun**
Please make sure these boxes are checked before submitting your PR, thank you!

* [ ] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [ ] Make sure you are merging your commits to `dev` branch.
* [ ] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by haoranyu** [comment]
Instead of `okText` / `okType`, `confirmButtonText` / `confirmButtonType` might be better naming which could be consistent with the naming of `confirm` in message-box component.

Similarly, a word `Button` could be insert into the naming of `cancelText` / `cancelType`, making them `cancelButtonText` / `cancelButtonType`.

**Comment by iamkun** [comment]
@haoranyu updated

**Comment by ChartWay** [comment]
怎么触发函数？点击确认就关闭下，没有触发处理逻辑？

**Comment by sulin2018** [comment]
> 怎么触发函数？点击确认就关闭下，没有触发处理逻辑？

同问 ?

**Comment by sulin2018** [comment]
> 怎么触发函数？点击确认就关闭下，没有触发处理逻辑？

看源码找到了:
```
@on-confirm="() => handleDelete(scope.$index)"
```

源码:
image

**Comment by heemoe** [comment]
Thank for you add this awesome feature.
But I guess `onConfirm/onCance` event probably should be adding to the official documents.

**Comment by wfucksky** [comment]
<el-popconfirm
                        title="这是一段内容确定删除吗？"
                        @onConfirm="() => delete()"
                        @onCancel="() => delete()"
                >
                    <el-button slot="reference">删除</el-button>
                </el-popconfirm> 

 delete() {
                console.log("delete");
            },
页面加载不出来了

**Comment by wfucksky** [comment]
`            delete() {
                console.log("delete");
            },
`
`                <el-popconfirm
                        title="这是一段内容确定删除吗？"
                        @onConfirm="delete"
                >
                    <el-button slot="reference">删除</el-button>
                </el-popconfirm>
` 
页面出不来了

**Comment by dmix** [comment]
This is great, I have so many places I'm going to be using this, replacing those invasive confirm dialogs! 

Really appreciate the work being done here.

**Comment by scscms** [comment]
这个组件多余了吧 this.$confirm 不香吗

**Pull request merged**
