### PR TITLE
Chore: Update package.json to lock lint config and fix console lint errors

### PR DESCRIPTION
**Pull request by syn-zeta**
Fixes about 80 lint errors. The [code style section in the contribution guidelines](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md#code-style) mentions that commits should comply with the existing ESLint configuration of Element, so the issues were resolved against the existing config, and the console has no lint warnings now.

I'd also noticed that there are quite a few failing unit tests, so I'll look into that as well. It'd be great to keep Element free of lint errors and failing unit tests.

* [x] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by syn-zeta** [comment]
Interesting that the CI build has failed but there were no errors when `npm run dist` was executed locally. I did also just notice that some tests did fail due to but due to other reasons than the one in the CI build logs.

**Comment by Leopoldthecoder** [comment]
Hi!

Recently I noticed there're some issues about lint errors. Strange thing is that the team has never experienced it: when we run `npm run dist`, there's no error.

I wonder why the community members are having this issue, so it'd be great if you could tell me:
- Did you pull the latest code before running `npm run dist`?
- Did you install the dependencies using `yarn` or `npm install`?
- What is the result of `npm ls eslint` and `npm ls eslint-config-elemefe` in your fork?
- Which version of `yarn` are you using?

**Comment by syn-zeta** [comment]
>Did you pull the latest code before running `npm run dist`?

Yes, I'd branched off from 1b3832f on `dev`.

>Did you install the dependencies using yarn or npm install?

Yes, I had the dev server running the whole time I was making the changes. The server was started using `npm run dev` which runs `yarn || npm i` via `bootstrap` at the beginning.

>What is the result of `npm ls eslint` and `npm ls eslint-config-elemefe` in your fork?
>Which version of yarn are you using?

```console
~/forked/element (lint)> npm ls eslint
element-ui@2.1.0 /Users/syn-zeta/forked/element
└── (empty)

~/forked/element (lint)> npm ls eslint-config-elemefe
element-ui@2.1.0 /Users/syn-zeta/forked/element
└─┬ cooking-lint@0.1.4
  └── eslint-config-elemefe@0.3.0

~/forked/element (lint)> yarn
bash: yarn: command not found

~/forked/element (lint)> npm --version
5.6.0

~/forked/element (lint)> node --version
v8.4.0

~/forked/element (dev)>
```

It's interesting that `eslint` is listed in `package.json` as a `devDependency` but does not get installed on `npm i`. I will try using `yarn` and see if it installs the packages properly and if there's any difference with the lint warnings in browser console. I also have `eslint` installed globally, so I'll also try removing that first and see if `npm i` installs that package locally or not.

**Comment by Leopoldthecoder** [comment]
```
~/forked/element (lint)> npm ls eslint-config-elemefe
element-ui@2.1.0 /Users/syn-zeta/forked/element
└─┬ cooking-lint@0.1.4
  └── eslint-config-elemefe@0.3.0
```
This is weird, because in `yarn.lock` we have [cooking-lint](https://github.com/ElemeFE/element/blob/dev/yarn.lock#L1604) locked to `0.1.3` and [eslint-config-elemefe](https://github.com/ElemeFE/element/blob/dev/yarn.lock#L2438) locked to `0.1.1`.

**Comment by syn-zeta** [comment]
Ah, but I haven't been using yarn. There is no `package-lock.json`, and `package.json` itself specifies [`"cooking-lint": "^0.1.3",`](https://github.com/ElemeFE/element/blob/dev/package.json#L77). The `^` will allow patch and minor version updates.

`cooking-lint`'s `package.json` specifies [`"eslint-config-elemefe": "*",`](https://github.com/cookingjs/cooking-lint/blob/master/package.json#L28), so basically it'll allow any release.

**Comment by Leopoldthecoder** [comment]
Then we'll tell people to install dependencies using `yarn`: https://github.com/ElemeFE/element/pull/9803 .

Could you verify if these lint errors still exist after you remove `node_modules` and reinstall them using `yarn`?

**Comment by syn-zeta** [comment]
Yes, using `yarn` installs the proper versions of `cooking-lint` and its dependency `eslint-config-elemefe`.

I think that `yarn` itself is not very common, so I thought it'd be good to fix `package.json` and not have to force users to install `yarn` as well. I've updated this PR so that the next time users run `npm run dev`, they'll get the same versions of the above packages as they're specified in `yarn.lock`. The commit was branched just before #9803:

image

Perhaps you may want to revert 9803 and use this PR instead.

**Comment by syn-zeta** [comment]
I'm still not sure why the Travis CI build is affected by lint config updates, and the results of `npm test` on my system (25 fails) is not the same as that of the CI build (1 failure):

```console
Chrome 64.0.3282 (Mac OS X 10.11.6): Executed 639 of 639 (25 FAILED) (57.746 secs / NaN secs)
TOTAL: 25 FAILED, 614 SUCCESS
```

**Comment by Leopoldthecoder** [comment]
CI build is now successful after I clicked the rebuild button. I guess it's because there're too many asynchronous assertions and sometimes travis doesn't have enough resource for our tests.

**Comment by syn-zeta** [comment]
I see.

`bootstrap` can be set back to `yarn || npm i` in a separate diff, I suppose. Thanks.

**Comment by Leopoldthecoder** [comment]
Sure.

**Pull request merged**
