### PR TITLE
Dialog: add modalAppendToBody

### PR DESCRIPTION
**Pull request by Leopoldthecoder**
Please makes sure these boxes are checked before submitting your PR, thank you!

* [ ] Make sure you follow Element's [Contributing Guide](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.md).
* [ ] Make sure you are merging your commits to `dev` branch.
* [ ] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by helloyou2012** [comment]
@Leopoldthecoder `1.2` 什么时候发布？

**Comment by Leopoldthecoder** [comment]
@helloyou2012 预计下周

**Comment by helloyou2012** [comment]
👍，现在由于这个问题导致 Dialog 样式错乱加了好多 hack，期待尽早发布把这些 hack 拿掉。。。。。

**Comment by gaolongxin062** [comment]
这个属性是不是没有用啊，看源码里面没有使用啊

**Pull request merged**
