### PR TITLE
Select: improve collapse-tags for more tags

### PR DESCRIPTION
**Pull request by yoyoys**
Please make sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer relative issues for you PR.

在相容原本 API 的前提下，加強了隱藏過多標籤的功能。
從原本只能顯示一個，改成可以顯示任意多個。

Improve collapse-tag options for numbers, 
So it can support more tag right now.

Example
image

### CODE REVIEW

**Comment by Leopoldthecoder** [comment]
Thanks for contributing, but this doesn't seem to be a common use case, so we may not support it.

**Comment by yoyoys** [comment]
Why not?
It’s will be a good use case for wide dropdown

**Comment by Opppex** [comment]
I agree. I would also like to expand the number of tags.

**Comment by bbbford** [comment]
This should be merged. This is a good improvement on the select component and has a definitive use case that everyone can benefit from.

**Comment by yoyoys** [comment]
@Leopoldthecoder After one year, is this feature still have no common use case? :)

**Comment by Anniywell** [comment]
I want to this feature

**Pull request closed without merging**
