### PR TITLE
Radio: fix doc, text-color,fill are Radio-group's props

### PR DESCRIPTION
**Pull request by hisland**
Please makes sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's [Contributing Guide](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.md).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Rebase before creating a PR to keep commit history clear.
* [x] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by baiyaaaaa** [comment]
Radio-group 哪有`text-color`和`fill`?

**Comment by hisland** [comment]
aaa
@baiyaaaaa 不会是我眼花了?

**Comment by baiyaaaaa** [comment]
@hisland 哈哈。。确实有，不好意思，看漏了

**Comment by hisland** [comment]
@baiyaaaaa 2个文件,一个中文,一个英文, 应该没有遗漏了😏

**Pull request merged**
