### PR TITLE
fix test after switching to yarn

### PR DESCRIPTION
**Pull request by Leopoldthecoder**
Please makes sure these boxes are checked before submitting your PR, thank you!

* [ ] Make sure you follow Element's [Contributing Guide](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.md).
* [ ] Make sure you are merging your commits to `dev` branch.
* [ ] Rebase before creating a PR to keep commit history clear.
* [ ] Add some descriptions and refer relative issues for you PR.

https://github.com/karma-runner/karma-phantomjs-launcher/issues/120#issuecomment-262634703

### CODE REVIEW

**Comment by QingWei-Li** [comment]
为啥 测试又没挂 🌚

**Comment by reverland** [comment]
...然后没merge我本地测试就跑不了了

**Comment by QingWei-Li** [comment]
@reverland 刪掉 node_module 然后用 yarn 安装依赖

**Comment by reverland** [comment]
@QingWei-Li 然而并不能用。。。还是按这个方式做的

**Comment by QingWei-Li** [comment]
@Leopoldthecoder 等杨老师解答了

**Comment by Leopoldthecoder** [comment]
本地参照这个 PR 改一下能跑吗？

**Comment by reverland** [comment]
可以

**Pull request closed without merging**
