### PR TITLE
ClickOutside: fix 'Cannot read property target of undefined'

### PR DESCRIPTION
**Pull request by Leopoldthecoder**
Please make sure these boxes are checked before submitting your PR, thank you!

* [ ] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md)).
* [ ] Make sure you are merging your commits to `dev` branch.
* [ ] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by Leopoldthecoder** [comment]
#4361

**Comment by wacky6** [comment]
看起来是无关的test挂了。

Menu horizontal的timeout应该改高一点。测试里面的setTimeout加起来1500了，CI负载高的话貌似很容易就超默认的2000？

这个的CI好像也是类似的问题
https://github.com/ElemeFE/element/pull/5390

**Comment by QingWei-Li** [comment]
那就把 timeout 改大一点 :滑稽:

**Comment by Leopoldthecoder** [comment]
续了一秒

**Pull request merged**
