### PR TITLE
Table: Add indeterminate & disabled state to multiple selection header checkbox

### LINKED ISSUE #9508: [Bug Report] Multi-select table's checkbox does not show indeterminate state as Transfer component
### Element UI version
2.0.11

### OS/Browsers version
OS X 10.11 / Chrome 62

### Vue version
2.5.13

### Reproduction Link
[https://jsfiddle.net/3jn2ftsz/](https://jsfiddle.net/3jn2ftsz/)

### Steps to reproduce
- In a multi-select table with more than one row, select one of the rows by clicking on the checkbox to the left.
- Notice that the select-all checkbox in the header does not indicate that some items in the table are checked.
- For [Transfer](http://element.eleme.io/#/en-US/component/transfer), notice that the checkbox in the header indicates with an indeterminate state that some items in the list below are checked.

### What is Expected?
Consistent UX of select-all checkbox in multi-select components like Table and Transfer.

### What is actually happening?
Multi-select Table's select-all checkbox does not have an indeterminate state when only some of the rows are checked.

### PR DESCRIPTION
**Pull request by syn-zeta**
This indeterminate state when only some rows are selected will make the component behavior consistent with that of the Transfer component.

Fixed #9508

* [x] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by syn-zeta** [comment]
The disabled checkbox still gets checked on click as the native event is handled instead of Checkbox's change event. What's the best place to address that?

**Comment by syn-zeta** [comment]
@QingWei-Li @Leopoldthecoder Requesting review for this small diff.

**Comment by syn-zeta** [comment]
Fixes #9508

**Comment by Leopoldthecoder** [comment]
Maybe for now we can ignore the disabled state. The header checkbox is only disabled when all rows are uncheckable, which does not happen quite often. Plus, computing if all rows are uncheckable may be a performance issue.

So you can remove line 37.

**Comment by syn-zeta** [comment]
@Leopoldthecoder Removed.

Although, the condition that existed to disable the checkbox was when no rows were visible in the table. Is that not a case when we would like to disable it?

**Comment by Leopoldthecoder** [comment]
@syn-zeta OK, I'll take care of that.

**Comment by JChermy** [comment]
请问有提供参数支持去掉table中的全选按钮吗？不只是在数据为空时disable

**Pull request merged**
