### PR TITLE
step: priority use icon from user provide, ignore current step status

### LINKED ISSUE #22449: [Bug Report] el-step组件的 status prop 指定值为 success 时,  指定的icon无法正常显示
### Element UI version
2.15.13

### OS/Browsers version
Windows 10 专业版  22H2       chrome 111.0.5563.65

### Vue version
2.6.14

### Reproduction Link
https://github.com/love596310898/learn-project/blob/master/element-ui/step.html

### Steps to reproduce
重现链接已提供
打开html -> first step component 不能正常显示 icon 图标  

### What is Expected?
期待可以正常显示通过icon指定的图标，并应用status prop 指定的状态

### What is actually happening?
指定status prop = success 时， 通过icon指定的图标无法正常显示

### PR DESCRIPTION
**Pull request by hickeyhub**
Please make sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [] Add some descriptions and refer relative issues for you PR.
[Closes #22449](https://github.com/ElemeFE/element/issues/22449)

### CODE REVIEW

**Comment by love596310898** [comment]
when status prop value is  sucess or error,  I think user-provided icon should be preferred.

**Comment by webvs2** [comment]
This can cause confusion in the operational state

**Comment by love596310898** [comment]
thanks for your feedback!
The default icon provided by the component should be used by default, and the operational status should be guaranteed by the user when the user provides icon and status

**Comment by love596310898** [comment]
> This can cause confusion in the operational state

thanks for your feedback!
The default icon provided by the component should be used by default, and the operational status should be guaranteed by the user when the user provides icon and status

**Pull request closed without merging**
