### PR TITLE
el-tree - lazy mode. Fixed: append, dragdrop. Added: node.close(), el-time-picker many bags fixed, added milliseconds, step, range

### PR DESCRIPTION
**Pull request by abernov**
Please make sure these boxes are checked before submitting your PR, thank you!

* [ ] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md)).
* [ ] Make sure you are merging your commits to `dev` branch.
* [ ] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by abernov** [comment]
Same bugs fixed in the tree component, lazy mode
1) append node (insertChild)
 a) fixed ISSUE 11346. - added condition !this.store.lazy to  if (!batch && !this.store.lazy) ...
 b) Since the new node does not require loading, was changed intital state for created not isLeaf node to
    loaded = true
    expanded = true 
 c) to append method of tree component
   - added new parameter - callback
   - added auto expand parent node 
2) Dragdrop (tree-node-drag-end)
 a) Dragdrop to collapsed node - to load dropNode children before drop events, was added dropNode.node.expand
 b) since in the lazy mode the node.data does not contain information about children, insertNode method uses node object  instead node.data.
3) node updateChildren - no node.data.children in the lazy mode
4) added method close(node) to tree component, it set node.loaded = false
  In large trees it is sometimes advantageous to transfer nodes to an unloaded state.

  Now it's easy to update the node: 
  node.close()
  node.expand()

**Comment by abernov** [comment]
Same bugs fixed in the tree component, lazy mode
1) append node (insertChild)
 a) fixed ISSUE 11346. - added condition !this.store.lazy to  if (!batch && !this.store.lazy) ...
 b) Since the new node does not require loading, was changed intital state for created not isLeaf node to
    loaded = true
    expanded = true 
 c) to append method of tree component
   - added new parameter - callback
   - added auto expand parent node 
2) Dragdrop (tree-node-drag-end)
 a) Dragdrop to collapsed node - to load dropNode children before drop events, was added dropNode.node.expand
 b) since in the lazy mode the node.data does not contain information about children, insertNode method uses node object  instead node.data.
3) node updateChildren - no node.data.children in the lazy mode
4) added method close(node) to tree component, it set node.loaded = false
  In large trees it is sometimes advantageous to transfer nodes to an unloaded state.

  Now it's easy to update the node: 
  node.close()
  node.expand()

**Comment by abernov** [comment]
check link
[example and test tree in lazy mode](https://jsfiddle.net/abernov/gee08hew/)

1) you can drag drop file and folder in any folder
2) create new file or folder
3) close folder

if uncomment <script src="//unpkg.com/element-ui@2.3.9/lib/index.js"></script>
this will not work!

**Comment by ziyoung** [comment]
@abernov Thanks for your contribution.
- I have closed issue #11346 , because I think it's not a bug.https://github.com/ElemeFE/element/issues/11346#issuecomment-392641561
- There is a bug when dragging and dropping a node to a collapse node the in lazy mode. I think you have fixed it.
- You add a new method called `node.close`. What's the use of this method?
- One pr with 14 commits, too many commits.

**Comment by abernov** [comment]
>You add a new method called node.close. What's the use of this method?

1. When a tree has thousands of nodes, it can require a lot of resources. 
In this case, the developer may want to close the collapsed nodes (loaded =false).
2. If several users work simultaneously with the tree, then it may be necessary to update the nodes.
Now it's easy to do
```
node.close()
node.expand()

```

**Comment by abernov** [comment]
If there is an error in the Backend, now you can cancel the download calling reject function

**Comment by abernov** [comment]
Added expand() method.

To reload tree node in the lazy mode use:
close(node)
expand(node)

**Comment by abernov** [comment]
example of use [https://jsfiddle.net/abernov/rzbd9kn8/](https://jsfiddle.net/abernov/rzbd9kn8/)

supports any formats:
 - with one digit, like **h:m:s** 
 - without hours, like **mm:ss**
- spaces between digits **HH : mm** 
- milliseconds added, **H:mm:ss.S** or **H:mm:ss.SS** or **H:mm:ss.SSS** 

added picker options:

```
 pickerOptions: {
       selectableRange: ['00:30:01.10 - 05:30:00.10'],
       steps: '00:00:00.04'
     }, 

```
selectableRange for is-range=true mode, allows you to limit the minimum and maximum time,
step - step for arrow-control="true"

used mouse wheel in picker when arrow-control="true"

**solved**
TimePicker step property #12913

**Pull request closed without merging**
