### PR TITLE
chore: init theme

### PR DESCRIPTION
**Pull request by iamkun**
Please make sure these boxes are checked before submitting your PR, thank you!

* [ ] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [ ] Make sure you are merging your commits to `dev` branch.
* [ ] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by stphdenis** [comment]
This two lines must have been inserted by error in `package.json` :
```json
  "engines": {
    "node": "8"
```

**Comment by iamkun** [comment]
@stphdenis Any detailed explanation please?

**Comment by mrJohnNova** [comment]
When installing element-ui@2.6.0 an error occurs:

> yarn upgrade v1.13.0
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error element-ui@2.6.0: The engine "node" is incompatible with this module. Expected version "8". Got "10.15.1"
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/upgrade for documentation about this command.

element-ui@2.6.0 only supports nodejs version 8? Seriously?

**Comment by iamkun** [comment]
Thanks, will fix soon.
In the mean time,  use npm or yarn --ignore-engines please.

**Pull request merged**
