### PR TITLE
Datepicker: add quarter picker

### PR DESCRIPTION
**Pull request by Adamwu1992**
add quarter picker

add quarter-picker test

delete todo notes

Please make sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by wacky6** [comment]
Please, first ask @Leopoldthecoder if this feature will be accepted.

If yes, at bare minimum:
* remove all `console.log`s
* remove commented (unused) code in your PR
* fix quarter format/parser, so is satisfies `date.getTime() === parser(formatter(input)).getTime()`, refer to week picker's formatter / parser if necessary
* document format 'Q' in format section
* DEFAULT_FORMAT should be i18n friendly, it should not contain non-ASCII characters

In my opinion, quarter picker should be a separate panel, it might be better to display it like this, you may need to communicate this issue with element designers on the layout / styling.

| | | | |
|---------|-----------|----------|----------|------------|
| 2016    | Q1        | Q2       | Q3       | Q4         |
| 2017    | Q1        | Q2       | Q3       | Q4         |
| 2018    | Q1        | Q2       | Q3       | Q4         |
| 2019    | Q1        | Q2       | Q3       | Q4         |

I'm not very enthusiastic about quarter picker, using date time point to represent an variable time length (90,91,92 depending on the year and time, see https://en.wikipedia.org/wiki/Calendar_year) is just not a good idea / practice to me.

If quarter is used for accounting purpose, and backend interprets it as 2018Q3, then it should be a select, not a date-picker.

**Comment by Adamwu1992** [comment]
You know there are companies is China pay tax on a quarterly basis. Last month we wanted to use a quarter picker on a tax management App and finally we implemented a quarter picker ourselves. 

Our backend (or frontend) interprets the value as a time range(eg: 2018-01-01 to 2018-03-31). The quarter picker is just like month picker (using date time point to represent a time range)

**Comment by hqzh** [comment]
@wacky6 pass?

**Comment by wacky6** [comment]
@iamkun @island205 

Need UX/UED on this issue. See comment https://github.com/ElemeFE/element/pull/10843#issuecomment-383801028

**Comment by iamkun** [comment]
@wacky6 参考了其他组件库 感觉季度选择不是很重要，现在是有什么需求要用到这个吗？ 还是我们也可以考虑不支持

**Comment by wacky6** [comment]
季度选择是之前社区提的，社区愿意做/维护可以加上。

我们这里没这个需求，我个人更倾向年选择+单选框。四个选项做picker没必要了

**Comment by iamkun** [comment]
那就暂时先不加了吧 再看看社区反馈

**Comment by bold881** [comment]
有需求，做报表的时候，计算同环比，需要用到季度选择器

**Comment by HawkingLan** [comment]
@iamkun 这个需求还挺常见的，在做BI分析时有很多季度同环比的场景，此外经济数据、财务数据等也都有按季度查看、比对、分析的场景

**Comment by liuruiqi1993** [comment]
同需要，也是报表里面，而且默认是上个季度。现在看来只能拆成两个下拉了

**Comment by MagicWang** [comment]
有需求，季度的同比、环比还是很有用的

**Comment by shaneYin** [comment]
同需要。这里有很多报表相关的业务需要从季度这一维度去比较和展示。

**Comment by zazzaz** [comment]
we will consider to add it to [Element Plus](https://github.com/element-plus/element-plus) for Vue 3 as a test

**Pull request closed without merging**
