### PR TITLE
pr #8940

### PR DESCRIPTION
**Pull request by kolesoffac**
Update code for #8940

### CODE REVIEW

**Comment by Leopoldthecoder** [comment]
Hi, thanks for contributing!

This fix is valid, but merging a big object may lead to some performance issues. 

I suppose we have two alternatives: we can replace

https://github.com/ElemeFE/element/blob/0d952b79174520957e86dc5f4bf6cccd96a58ca0/packages/table/src/table-store.js#L349-L351

with

```JS
Vue.set(states, 'leafColumnsLength', leafColumns.length);
Vue.set(states, 'fixedLeafColumnsLength', fixedLeafColumns.length);
Vue.set(states, 'rightFixedLeafColumnsLength', rightFixedLeafColumns.length);
```

Or simply declare these 3 keys when initiating `this.states`:
https://github.com/ElemeFE/element/blob/0d952b79174520957e86dc5f4bf6cccd96a58ca0/packages/table/src/table-store.js#L83-L109

I prefer the second approach, what do you think?

**Comment by kolesoffac** [comment]
I think, that first with Vue.set.

**Comment by liril-net** [comment]
I do believe that the second one would be better. Cause state data flow can be controlled in this way.

**Comment by Leopoldthecoder** [comment]
@kolesoffac I took the liberty of updating this PR to my proposal, hope you don't mind. Again, thanks for your contribution.

**Pull request merged**
