### PR TITLE
Support SSR

### PR DESCRIPTION
**Pull request by QingWei-Li**
Please makes sure these boxes are checked before submitting your PR, thank you!

* [ ] Make sure you follow Element's [Contributing Guide](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.md).
* [ ] Make sure you are merging your commits to `dev` branch.
* [ ] Rebase before creating a PR to keep commit history clear.
* [ ] Add some descriptions and refer relative issues for you PR.

等龙哥的 `wind-dom` 放出来后，加两行判断就搞定了

### CODE REVIEW

**Comment by reverland** [comment]
说好的没打算支持ssr呢？233

**Comment by baiyaaaaa** [comment]
感觉这种到处插`$isServer`的很不优雅呀，有没有别的姿势

**Comment by QingWei-Li** [comment]
@baiyaaaaa 反正就是想达到遇到 DOM 的地方就跳过，否则就正常渲染。如果在服务端 mock 一个 window 对象也是可以的，但是对用户不够友好。有其他想法么

**Comment by chuangker** [comment]
@QingWei-Li 
比较关心什么时候能支持ssr
如果是 1.1 开始支持，什么时候能发布

**Comment by QingWei-Li** [comment]
@chuangker 元旦前

**Pull request closed without merging**
