### PR TITLE
TabPane: add support for destroying after switching

### PR DESCRIPTION
**Pull request by thelastto**
Please make sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by Kingwl** [comment]
https://github.com/ElemeFE/element/issues/12642

**Comment by Kingwl** [comment]
@ziyoung 
hi, 还有一个问题, 其实这个`tab-pane`的`lazy`还有`destroy`属性可以在组件内部的`slot`中实现,
这样就不需要`loaded `这个额外的变量来判断是否加载成功

我或 @thelastto  会在另一个PR中进行这个小重构🤷🏻‍♂️

**Comment by ziyoung** [comment]
@Kingwl 如果在 `slot` 处理的话，感觉 destroy 与 lazy 属性甚至有些多余了。😅

**Comment by Kingwl** [comment]
> 感觉 destroy 与 lazy 属性甚至有些多余了  

这两个其实是不多余的...因为还是要控制这两个行为
多余的是`loaded`, 因为`panel`component始终存在, 并且之前的bug(s)都可以直接修掉

**Comment by benjamin79** [comment]
any update?

**Pull request closed without merging**
